### ISSUE TITLE
[deferred delete] Deferred delete doesn't delete all files requested

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#630] opened 2020-07-12 23:27 UTC
**Small description**
Deferred delete of files doesn't delete all files when committing sheet.

**Expected result**
All files marked for deletion are deleted.

**Actual result with screenshot**
It deletes all but one of the files.

**Steps to reproduce with sample data and a .vd**
```
touch a b
vd .
# delete both  files,
# commit-sheet
# vd will ask if you want to delete 2 files, say yes, 
# Only one file will be deleted
```

**Additional context**
Please include the version of VisiData.  Latest develop version.

**Comment by anjakefala** [comment] 2020-07-15 21:56
Hi @frosencrantz!

I thought something was funny. I thought I tested this case, and then thought, "I guess I forgot it".

Except, I am actually unable to reproduce the bug. My gut instinct is that you are closing VisiData before the deletes complete.

@saulpw, should we add a blocker against quitting for incomplete DirSheet commits?

**Comment by anjakefala** [comment] 2020-07-18 05:49
I spoke with @saulpw. We are going to try to figure out a safety quit mechanism for this.

**Comment by frosencrantz** [comment] 2020-07-19 22:09
Anja, thanks for looking.

I still see the problem.   I can consistently reproduce that not all files are deleted in certain cases.

Here is a visual of what it looks like to me:
	https://asciinema.org/a/NLV7FTnK8PuiDKoWqfLGab5OO
	https://asciinema.org/a/sRgSROa9mujKW7QmYjUGhsNTC

What do you make of this?  Is there a way I could tell if I exit too soon?

**Comment by anjakefala** [comment] 2020-07-21 01:38
![Peek 2020-07-20 18-38](https://user-images.githubusercontent.com/7489659/88002811-40e89900-cab8-11ea-9c98-be44f946a81c.gif)

Very weird!

**Comment by anjakefala** [comment] 2020-07-21 01:49
> What do you make of this? Is there a way I could tell if I exit too soon?

Your videos were super helpful. I am now convinced a premature exist is possibly not the issue. Based on the "deleted x files" status, where `x =< nSelected/2`. I do not know why only half are being deleted for you, and all of them are being deleted for me. I will try to figure it out!

**Comment by anjakefala** [comment] 2020-07-21 01:50
Figured it out. The bug is with `gs` `gd`. Individual selection, and then `gd` is fine. Thanks so much for the asciinemas @frosencrantz, that really helped me with narrowing this down.

**Comment by anjakefala** [comment] 2020-07-21 03:38
Should be fixed. =)

**Closed as completed by anjakefala** 2020-07-21 03:38 UTC
Labels: bug, fixed
