### ISSUE TITLE
cannot undo the first modification to a sheet-specific HelpSheet

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1820] opened 2023-03-24 01:02 UTC
**Small description**
After `help-commands` or `options-sheet`, the first modification to the sheet cannot be undone with `undo-last`.

**Expected result**
I expect that the modification would be undone as usual.

**Actual result with screenshot**
The command is not undone, and Visidata shows the message "nothing to undo on current sheet".

**Steps to reproduce with sample data and a .vd**
Open any sheet, and run:
`help-commands`, `addcol-incr`, `undo-last`
or
`options-sheet`, `addcol-incr`, `undo-last`

**Additional context**
saul.pw/VisiData v2.12dev

`help-commands` has the problem, but `help-commands-all` does not.
`options-sheet` has the problem, but `options-global` does not.
The reason for the difference that `help-commands` creates a `HelpSheet` with `source=sheet`. So at the time that the HelpSheet is created, `sheet.cmdlog.rows` already contains something, the commands that created and modified the source sheet. Since `sheet.cmdlog.rows` is not empty, `help-commands` is not added to the sheet-specific cmdlog:
https://github.com/saulpw/visidata/blob/b810fe423c3514c46222eed9d4b5a540e9805e46/visidata/cmdlog.py#L217-L220

I have an exploratory patch that seems to fix the undo behavior for `help-commands` and `options-sheet`:  
https://github.com/saulpw/visidata/commit/c621eb4e1bfc687aa7262de279d5e613d4214cb7. But I don't know enough about the internals of Visidata to know if it is an appropriate fix.

**Comment by saulpw** [comment] 2023-03-24 17:02
Thanks for the report, @midichef!  Your fix makes some sense to me.

I'm wondering, though, maybe line 217 should also (or instead) check `sheet.cmdlog_sheet`?  Then the cmdlog `help-commands` would be more like `help-commands-all`, with its sheet creation command added.  This seems like the more root cause.  Does this fix this issue similarly, or is there something I've missed?

**Comment by midichef** [comment] 2023-03-27 01:19
I updated my comment to link directly to the patch I'm proposing (https://github.com/saulpw/visidata/commit/c621eb4e1bfc687aa7262de279d5e613d4214cb7) instead of the branch it is on, which will go away soon.
It sounds like we are thinking along the same lines. Let me know if there's more to be addressed.

**Comment by anjakefala** [comment] 2023-03-31 16:20
This should be fixed now, @midichef! Thanks for the report.

**Closed as completed by anjakefala** 2023-03-31 16:20 UTC
Labels: bug, fixed
