### ISSUE TITLE
vd 2.develop: installed plugins not listed

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#519] opened 2020-04-23 15:38 UTC
Hi,
I have just installed the 2.develop version, and then installed via bazar (great thing) vddedupe plugin.

Then I have closed vd and opened it again and I have no check in the installed column. If I try to install again vd alerts me ("plugin path already exists ...").

Is it normal?

Thank you

![image](https://user-images.githubusercontent.com/30607/80118662-050d6880-8589-11ea-9716-b0b547196858.png)

**Comment by anjakefala** [comment] 2020-04-23 16:29
It bug.

Thank you for posting!

**Comment by aborruso** [comment] 2020-04-24 06:07
@anjakefala after installing a plugin using the vd bazar, I have the plugin file in `~/.visidata/plugins` folder, but I do not have any `.visidatarc` file. 
Probably in vd 2, you do not use this file for plugins and the right file is `__init__.py`. Am I right?

Thank you

**Comment by anjakefala** [comment] 2020-04-24 06:25
As it stands, you do need a `from plugins import *` in your `~/.visidatarc`, but I think we are going to change that. Stay tuned! :eyes:

**Comment by aborruso** [comment] 2020-04-24 06:28
@anjakefala I'm testing a plugin and I do not know if it does not work properly because I do not have `~/.visidatarc` file. I have only `__init__.py`. For this reason I'm asking about it.

**Comment by anjakefala** [comment] 2020-04-24 06:32
Yeah! You need a `~/.visidatarc` with a `from plugins import *` within it.

But I just made an issue that will hopefully remove that requirement in the future. But for now, yes you totes need that.

**Comment by aborruso** [comment] 2020-04-24 06:37
@anjakefala in the [jeremy guide](https://jsvine.github.io/intro-to-visidata/advanced/extending-visidata/#how-to-install-a-plugin) I read that I can write simply `import myplugin`. Is it this also a right way?

**Comment by anjakefala** [comment] 2020-04-26 02:19
Jeremy's guide is for how things work from the table branch. =) Closing this for now because we figured out the cause! You were not actually importing the plugins.

**Closed as completed by anjakefala** 2020-04-26 02:19 UTC
Labels: bug
