### ISSUE TITLE
[loaders postgres] Transaction error when viewing table

### ISSUE THREAD

**Issue by kbd** [saulpw/visidata#727] opened 2020-10-14 21:30 UTC
```
$ vd --version
saul.pw/VisiData v2.0.1
```

After executing:

```
$ vd postgres://user@localhost:port/database --postgres-schema=schema
```

I get a correct list of the tables, but when I hit enter to view a table VisiData shows no data and I get the following error:

> psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

![Screen Shot 2020-10-14 at 3 20 38 PM](https://user-images.githubusercontent.com/728060/96046598-fe252b80-0e30-11eb-9ca4-9c468ee0919a.png)

Here's the traceback:

![Screen Shot 2020-10-14 at 3 23 46 PM](https://user-images.githubusercontent.com/728060/96046884-712ea200-0e31-11eb-99f0-1912db813281.png)

I'm able to view the same tables using DBeaver with no problem.

**Comment by saulpw** [comment] 2020-10-19 07:49
Hi @kbd, thanks for the bug report. I don't have this problem but my Postgres test rig is very simplistic. Have you been able to investigate this any further?

**Comment by kbd** [comment] 2020-10-19 08:26
@saulpw got the project set up locally but didn’t start digging into the Postgres loader yet. Will continue looking into it tomorrow.

**Comment by saulpw** [comment] 2020-11-23 23:01
Closing until there is more information or I have a test setup that exhibits the issue.

**Comment by jdormit** [comment] 2020-12-27 01:53
I've reproduced this. It looks like the Postgres integration isn't correctly accounting for the `--postgres_schema` when executing SQL to populate the sheet for a table. Here's how I reproduced:

1. Open a Postgres database with some tables within a schema via `vd postgres://user:password@host:5432/database --postgres_schema=my_schema`. The list of tables in the schema is correctly populated when VisiData opens.
2. Navigate to any table and enter it via `<return>`. The table will be blank when it opens.
3. View recent errors via `<C-e>`. You'll see this stacktrace:

```
Traceback (most recent call last):
  File "/Users/jdormit/.local/pipx/venvs/visidata/lib/python3.9/site-packages/visidata/threads.py", line 215, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/jdormit/.local/pipx/venvs/visidata/lib/python3.9/site-packages/visidata/loaders/postgres.py", line 115, in reload
    with self.sql.cur("SELECT * FROM " + self.source) as cur:
  File "/Users/jdormit/.local/pipx/venvs/visidata/lib/python3.9/site-packages/visidata/loaders/postgres.py", line 63, in cur
    cur.execute(qstr)
psycopg2.errors.UndefinedTable: relation "<tablename>" does not exist
LINE 1: ...ECLARE "PJRYYV" CURSOR WITHOUT HOLD FOR SELECT * FROM <tablename>
                                                                 ^
```

As seen in this stacktrace, VisiData is executing a `SELECT * FROM <tablename>`, when it should be executing a `SELECT * FROM <schema>.<tablename>`.

This also seems to poison the `psycopg2` connection object, as any subsequent SQL that attempts to execute fails with the `current transaction is aborted` error mentioned above.

**Comment by anjakefala** [comment] 2020-12-30 00:50
Fixed has been implemented on develop by @jdormit. =) Will be part of the next release.

**Closed as completed by anjakefala** 2020-12-30 00:50 UTC
Labels: bug
