### ISSUE TITLE
BrokenPipeError on writing to stdout

### ISSUE THREAD

**Issue by robdmc** [saulpw/visidata#851] opened 2020-12-26 18:25 UTC
**Small description**
When writing larger files to stdout, vd throws a Broken pipe Error.

**Expected result**
```
seq 100 | awk 'BEGIN{print "x,y"} {print $1","2*$1}' | vd -f csv -b - | head
opening - as csv
I shall never get to twenty at that rate!
saving 1 sheets to - as tsv
- save finished
x       y
1       2
2       4
3       6
4       8
5       10
6       12
7       14
8       16
9       18
```
This works fine.

**Actual result with screenshot**
But now look what happens if I do this for a larger input.
```
 seq 10000 | awk 'BEGIN{print "x,y"} {print $1","2*$1}' | vd -f csv -b - | head
opening - as csv
saving 1 sheets to - as tsv
x       y
1       2
2       4
3       6
4       8
5       10
6       12
7       14
8       16
9       18
Traceback (most recent call last):
  File "/home/rob/envs/base/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/rob/envs/base/lib/python3.8/site-packages/visidata/main.py", line 299, in vd_cli
    rc = main_vd()
  File "/home/rob/envs/base/lib/python3.8/site-packages/visidata/main.py", line 284, in main_vd
    saveSheets(outpath, vd.sheets[0], confirm_overwrite=False)
  File "/home/rob/envs/base/lib/python3.8/site-packages/visidata/vdobj.py", line 37, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/home/rob/envs/base/lib/python3.8/site-packages/visidata/save.py", line 105, in saveSheets
    return vd.execAsync(savefunc, givenpath, *vsheets)
  File "/home/rob/envs/base/lib/python3.8/site-packages/visidata/main.py", line 198, in <lambda>
    vd.execAsync = lambda func, *args, **kwargs: func(*args, **kwargs) # disable async
  File "/home/rob/envs/base/lib/python3.8/site-packages/visidata/loaders/tsv.py", line 73, in save_tsv
    fp.write(unitsep.join(dispvals.values()))
BrokenPipeError: [Errno 32] Broken pipe
```
I haven't looked at the code, but could this be due to async issues with writing to stdout?

**Comment by anjakefala** [comment] 2021-01-01 20:34
@robdmc Thanks for providing an easy way to reproduce the problem!

**Comment by anjakefala** [comment] 2021-01-01 20:38
Interestingly,

```
seq 10000 | awk 'BEGIN{print "x,y"} {print $1","2*$1}' | bin/vd -f csv -b - | head
```

has a broken pipe error, but

```
seq 10000 | awk 'BEGIN{print "x,y"} {print $1","2*$1}' | bin/vd -f csv -b - | cat
```

does not. Which makes me think that something is happening on head's end, where it closes the pipe (because it got enough content to print the top x), and VisiData does not handle gracefully the closed output pipe.

**Comment by anjakefala** [comment] 2021-01-01 20:42
> Once head has read enough lines from it's stdin (stdout of ls), then it exits and therefore closes the stdin. 
When that happens, the pipe is considered to be broken and ls receives a SIGPIPE signal. As a reaction to that it terminates as well, way before processing everything that it would normally do. 

https://stackoverflow.com/questions/32341733/does-piping-ls-to-head-stop-its-execution-half-way

**Comment by anjakefala** [comment] 2021-01-02 06:15
This should now be fixed on develop, and will be part of the next release! Thanks for the bug report. =)

**Closed as completed by anjakefala** 2021-01-02 06:15 UTC
Labels: bug
