### ISSUE TITLE
Incomplete descriptions in commands.tsv

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#329] opened 2019-08-11 16:54 UTC
**FYI: github says there are problems with commands.tsv**

**Expected result**
table viewer in github ui.

**Actual result with screenshot**

We can make this file beautiful and searchable if this error is corrected: It looks like row 94 should actually have 12 columns, instead of 11. in line 93.

https://github.com/saulpw/visidata/blob/develop/visidata/commands.tsv

**Comment by anjakefala** [comment] 2019-08-11 17:45
@frosencrantz Wanna make a PR on develop? O=)

**Comment by anjakefala** [comment] 2019-08-18 20:13
The issue is that some commands are missing descriptions.

**Comment by saulpw** [comment] 2019-10-05 20:57
We've decided to move the command helpstrings back into the code and deprecate `commands.tsv`, as it's a pain to maintain separately.

**Comment by frosencrantz** [comment] 2019-10-27 21:29
@saulpw, I understand.  This was mostly intended as FYI.   It would have been nice to have the code look prettier in Github.

I really like commands.tsv.   As part of learning to use Visidata I use it as a good data sample and use it to look up commands all the time.  I've thought it would make a great data source for a Visidata tutorial.

Some comments/requests:

* commands.tsv is complete. My impression is that z^H only gives a subset of commands.tsv.  Maybe limited to the types of active table types?  Not sure.  It would be helpful if z^H was also complete. 
 I can log a bug or features request about this if you want.
* I like that it has extra info like which of your youtube videos references a command.
* Please add tests to make sure z^H is giving reasonable results.  I can log a feature request for this.  I'm not sure what would be involved to write such a test.
* One of the problems seems to have been loading the file without having problems due to options/user supplied flags.  But this seems like a problem that needs be solved anyways.  Plugins are loaded as a data table.  And I can see how attractive it mightx be to load data for other features.

**Comment by anjakefala** [comment] 2019-10-28 01:35
```
 I understand. This was mostly intended as FYI. It would have been nice to have the code look prettier in Github.
```

@frosencrantz, can one file an issue against GitHub? :joy: It feels like tsvs having missing values is part of the tension of life, and GitHub would be such a joyful place if it took that into account! 

```
I really like commands.tsv. As part of learning to use Visidata I use it as a good data sample and use it to look up commands all the time. I've thought it would make a great data source for a Visidata tutorial.
```

I am glad that it is liked. :blush:  It took us a while to build it! You are right that it would make a cute data source for a tutorial.

I like it too, actually. It was really useful for us to build when @saulpw was working on undo (it provided a neat list of Modifying Data Commands). Also, visually seeing the relationships between commands, helped us out with clarifying the 2.0 longname design.

The issue is that maintaining it (and updating it) became Toil Work because it was separate from the code and double the work of making an adjustment to commands. We want to decrease the amount of Toil, because otherwise the joy gets sucked out of devoting time to VisiData.

```
commands.tsv is complete. My impression is that z^H only gives a subset of commands.tsv. Maybe limited to the types of active table types? Not sure. It would be helpful if z^H was also complete.
I can log a bug or features request about this if you want.
```

As of today, it is a feature, not a bug! `z^H` shows the available commands for the current sheet.

```
I like that it has extra info like which of your youtube videos references a command.
```

Oh, yay. I re-watched every single video to add that info. :D :D I am glad it was useful to someone.

```
One of the problems seems to have been loading the file without having problems due to options/user supplied flags. But this seems like a problem that needs be solved anyways. Plugins are loaded as a data table. And I can see how attractive it mightx be to load data for other features.
```

I agree that this is reasonable. I would appreciate it if someone could compile a list of options that they found broke the plugins/commands.tsv sheets, and then opened an issue listing them. So far, I can confirm that `--delimiter` being set to something other than `\t` breaks the **PluginsSheet**, so I am going to fix that!

**Comment by anjakefala** [comment] 2019-11-01 04:37
```
I would appreciate it if someone could compile a list of options that they found broke the plugins/commands.tsv sheets, and then opened an issue listing them. So far, I can confirm that --delimiter being set to something other than \t breaks the PluginsSheet, so I am going to fix that!
```

In anticipation of this work, we create a system tsv sheet that all system tsvs can inherit from: https://github.com/saulpw/visidata/commit/7c5febb4068852e81c6a13991af9a878f0d33de4.

If we find any options that need default setting, we can set them in one place there. =)

**Comment by anjakefala** [comment] 2019-11-01 04:42
Closing for reasons outlined in above comments.

**Closed as completed by anjakefala** 2019-11-01 04:42 UTC
Labels: bug

**Comment by saulpw** [comment] 2019-11-01 05:07
@frosencrantz: `z Ctrl+H` only shows commands available on the current sheet, by design. There could be a `g Ctrl+H` or something that shows all commands.  I wish we could keep the other metadata up-to-date too, but we don't have the bandwidth..

**Comment by frosencrantz** [comment] 2019-11-12 00:16
@anjakefala 😂

 > @frosencrantz, can one file an issue against GitHub? 😂 It feels like tsvs having missing values is part of the tension of life, and GitHub would be such a joyful place if it took that into account!
> 

Yes, that makes a sense.  I'm not sure how to tell github they should just present the data nicely.  I opened a case with github, we'll see what they say.  I'm not sure if there is a repo I can report an issue on.

> The issue is that maintaining it (and updating it) became Toil Work because it was separate from the code and double the work of making an adjustment to commands. We want to decrease the amount of Toil, because otherwise the joy gets sucked out of devoting time to VisiData.

Yes, please find "joy" in working on this project.  It is a joy to use, and hopefully you and @saulpw and other contributors enjoy working on it.  It reminds me of a comment in a video from Bram Moolenaar, someone asked him why vim survived when many other vi-clones failed...  https://youtu.be/p6K4iIMlouI?t=3716
 
> ```
> I like that it has extra info like which of your youtube videos references a command.
> ```
> 
> Oh, yay. I re-watched every single video to add that info. :D :D I am glad it was useful to someone.

Yes, thank you very much!  I've used it several times to go back to watch Saul demonstrate visidata.
It is a little hard to find.  It might be useful to put that in the user docs somewhere.


> I agree that this is reasonable. I would appreciate it if someone could compile a list of options that they found broke the plugins/commands.tsv sheets, and then opened an issue listing them. So far, I can confirm that `--delimiter` being set to something other than `\t` breaks the **PluginsSheet**, so I am going to fix that!

You already know about: https://github.com/saulpw/visidata/issues/323
It looks like things were broken again for a week or so recently, but was working again the last time I checked.  

I will suggest a test of some sort for the help table, just to make sure it has some reasonable values. Broken record, I am.   <(°.°)>  

I've opened a feature request based on @saulpw's  suggestion for a `g Ctrl+H`:  
   https://github.com/saulpw/visidata/issues/393
