### ISSUE TITLE
[2.4-dev] When scrolling with mouse, if the top of the sheet is hit, vd freezes for a few seconds

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#568] opened 2020-05-21 14:22 UTC
I've noticed that if I scroll down a little, then scroll up with the mouse, if the selected row hits the top of the sheet (row 1) vd will freeze for a few seconds, then come back to normal.

**Comment by anjakefala** [comment] 2020-06-01 04:47
Hey @geekscrapy! Thanks for filing this issue.

I have not been able to reproduce the problem. =/ So I am going to close this issue for now!

**Closed as completed by anjakefala** 2020-06-01 04:47 UTC
Labels: bug, can't reproduce

**Comment by geekscrapy** [comment] 2020-06-01 05:06
No problem, I think it might be something to do with OSX and it's accelerated scrolling. When it hits the top OSX keeps sending the scroll sig to the app for a while afterwards to simulate it slowing down. My assumption (and that's all it is!) is that when it hits the top of the sheet, OSX simulates the slow down for a few seconds. It seems that the harder I scroll up, the longer I have to wait.
Keep this closed for now, I'll try with a normal mouse 🙃

https://osxdaily.com/2011/11/29/disable-inertia-scrolling-in-mac-os-x-lion/

**Comment by anjakefala** [comment] 2020-06-01 05:09
Ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.

Nice debugging. This verifies why I cannot reproduce it.

**Comment by geekscrapy** [comment] 2020-06-01 05:12
Does any of the maintainers have OSX? I have no idea really where to start to look at this...

**Comment by anjakefala** [comment] 2020-06-01 05:18
No. =( I am sorry. You can check in #visidata, but Saul and I are both Linuxers.
