### ISSUE TITLE
How to connect to postgres using vdsql

### ISSUE THREAD

**Issue by RichardNicolas** [saulpw/visidata#1854] opened 2023-03-13 11:02 UTC
Under Ubuntu 20 and python 3.8

Installation (as of 2023-03-13) with:
`pip3 install 'ibis-framework[postgres]'`
`pip3 install git+https://github.com/visidata/vdsql.git`

I ran : `vdsql -N 'postgresql://username:password@localhost:5432/mydb'`

Connection to database is working but it seems to launch classical visidata: tables are fully loaded in visidata and commands like `sidebar-toggle` are unknown.

**Comment by anjakefala** [comment] 2023-04-19 04:13
@saulpw or @cpcloud  Do you remember how connecting to `postgres` worked for `vdsql`? Did it work via url? 

Note to self: for `ibis`, you would connect to postgres via URL via the `set_backend` command:

```
    >>> ibis.set_backend("postgres://user:password@hostname:5432") 
```

**Comment by anjakefala** [comment] 2023-04-19 04:14
Duplicates  #1743

**Comment by anjakefala** [comment] 2023-04-19 04:15
Duplicate of https://github.com/saulpw/visidata/issues/1743

**Comment by saulpw** [comment] 2023-07-07 01:20
This should be working with vdsql now, as of df3d8a0cb1809a2f10888c089ccc4c794cd064c3.

**Closed as completed by saulpw** 2023-07-07 01:20 UTC
Labels: bug, fixed, vdsql
