### ISSUE TITLE
PostgreSQL database shows no tables

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1743] opened 2023-02-19 08:11 UTC
Connecting to this Postgres database shows no tables:

```
vd postgres://reader:NWDMCE5xdipIjRrp@hh-pgsql-public.ebi.ac.uk:5432/pfmegrnargs
```

Same error happens with `vdsql`. I used `psql` to confirm this database has tables.

**Comment by anjakefala** [comment] 2023-04-19 03:55
@cool-RR This is a remote public postgres server?

**Comment by anjakefala** [comment] 2023-04-19 04:15
Duplicate of #1854

**Comment by cool-RR** [comment] 2023-04-20 11:09
@anjakefala Yes it is. You can simply run the command I included in the first message.

I'm not sure why you marked the two issues as duplicates of each other. They might be related but the content seems different.

**Comment by anjakefala** [comment] 2023-04-20 17:02
They will both be addressed by the same bugfix, and I am struggling to keep track of all of the issues.

**Comment by saulpw** [comment] 2023-07-07 01:18
I don't know why `vd` shows no tables, but `vdsql` works now as of df3d8a0cb1809a2f10888c089ccc4c794cd064c3 (it was not replacing vd functionality with its own).

**Closed as completed by saulpw** 2023-07-07 01:18 UTC
Labels: bug, fixed, vdsql
