### ISSUE TITLE
renaming a frequency sheet is not stored correctly in a log file

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#979] opened 2021-05-09 07:48 UTC
**Small description**

Hi,
I have two input TSV file, named `one` and `two`. I run these steps:

- I open `one` and I set the column `com_istat` as key column;
- I do the same for `two` and the column `cod_istat`;
- I run an inner join for `one` and `two` and I have an output join table;
- Starting from this join table I create a frequency table based on `Denominazione` field;
- I rename this frequency table in `result`;
- I save this table as `result.tsv`;
- I save the log of this process in `result.vd`.

Then if I run `vd -y -b -p result.vd` I have `no sheet named result`: vd does not find the source table to save, and I have no output.

**Expected result**

To have the output file. I know, I could not rename the file and I could run simply `CTRL+s` and save it. But it seems to me there is something wrong in the creation of the log.

**Actual result with screenshot**

![image](https://user-images.githubusercontent.com/30607/117564246-7a23e100-b0ab-11eb-8d8e-92bbf361da60.png)

**Steps to reproduce with sample data and a .vd**

[Here](https://github.com/saulpw/visidata/files/6447096/result.zip) my input files, the two tables and the log.

**Additional context**

saul.pw/VisiData v2.5dev

**Comment by anjakefala** [comment] 2021-06-14 05:44
Thanks @aborruso!

Thanks to the .vd you added to the issue, I was able to quickly diagnose the problem. `rename-sheet` should have the previous sheet name in its `sheet` column. This bug is fixed for future constructions of cmdlogs.

You will need to change that entry in the cmdlogs that you have! This fix is on `develop`, and will be part of the next release.

**Comment by aborruso** [comment] 2021-06-14 06:26
@anjakefala thank you, I have tested [using these files](https://github.com/saulpw/visidata/files/6646027/result.zip) and when I run `vd -y -b -p result.vd` now I have `no choice made` error:

```
opening result.vd as vd
"one"
opening one as txt
toggle current column as a key column
open input in VisiData
"two"
opening two as txt
toggle current column as a key column
open Sheets Stack: join or jump between the active sheets on the current stack
select current row
selected 1 sheets
select current row
selected 1 more sheets
merge selected sheets with visible columns from all, keeping rows according to jointype
no choice made
replay aborted during join-sheets
```

It is as if the join choice was not read correctly

**Comment by geekscrapy** [comment] 2021-06-14 07:05
I think this is is due to #914

**Comment by aborruso** [comment] 2021-06-14 08:30
@anjakefala I have updated vd and I have again

```
opening result.vd as vd
"one"
opening one as txt
toggle current column as a key column
open input in VisiData
"two"
opening two as txt
toggle current column as a key column
open Sheets Stack: join or jump between the active sheets on the current stack
select current row
selected 1 sheets
select current row
selected 1 more sheets
merge selected sheets with visible columns from all, keeping rows according to jointype
no sheet named result
replay canceled
```

I have used the same input file

**Comment by aborruso** [comment] 2021-06-14 08:30
> I think this is is due to #914

thank you

**Comment by anjakefala** [comment] 2021-06-14 17:14
Unfortunately, you are going to need to share with me what your new vd is. =( At least, the `rename-sheet` row. I am not sure what is going on from the replay logs.

**Comment by aborruso** [comment] 2021-06-14 17:32
@anjakefala my new vd is this

```
sheet	col	row	longname	input	keystrokes	comment
global		null_value	set-option			
			open-file	one	o	
one	com_istat		key-col		!	toggle current column as a key column
			open-file	two	o	open input in VisiData
two	cod_isat		key-col		!	toggle current column as a key column
two			sheets-stack		S	open Sheets Stack: join or jump between the active sheets on the current stack
sheets		キtwo	select-row		s	select current row
sheets		キone	select-row		s	select current row
sheets			join-sheets	inner	&	merge selected sheets with visible columns from all, keeping rows according to jointype
result			rename-sheet	result		rename current sheet to input
result			save-sheet	result.tsv	^S	save current sheet to filename in format determined by extension (default .tsv)

```

thank you

**Comment by anjakefala** [comment] 2021-06-14 19:02
```
result			rename-sheet	result		rename current sheet to input
```

Needs to be

```
name_of_joined_sheet			rename-sheet	result		rename current sheet to input
```

Where `name_of_joined_sheet` is the name of the sheet before it was renamed. This was the change I asked you to make in my reply! =) Sorry, if that was not clear. If you update to the most recent `develop`, and remake the .vd using that version of VisiData, it will do that automatically.

**Comment by aborruso** [comment] 2021-06-14 19:11
@anjakefala I have not changed anything, because this morning I had done the vd update. In addition to updating, do I have to change the file?

```
pip3 install --upgrade  git+https://github.com/saulpw/visidata.git@develop
```

**Comment by anjakefala** [comment] 2021-06-14 20:08
Yes! The update fixes the generation of future .vds, but VisiData is still going to have the same struggle with a malformed .vd.

**Comment by aborruso** [comment] 2021-06-14 20:19
> Yes! The update fixes the generation of future .vds, but VisiData is still going to have the same struggle with a malformed .vd.

This morning I have generated the last vd file with the new visidata

**Comment by anjakefala** [comment] 2021-06-14 20:45
Is there any chance it is an environment problem? =( I cannot reproduce. Sorry aborruso.

**Comment by aborruso** [comment] 2021-06-14 21:44
> Is there any chance it is an environment problem? =( I cannot reproduce. Sorry aborruso.

it's a debian 11.0

**Comment by aborruso** [comment] 2021-06-15 06:07
@anjakefala a screencasting of the process on my PC http://youtu.be/leq7MCKfPB4?hd=1

How can i be sure that my VisiData version has the code changes you made? What file could I inspect?

If I run `vd --version` I have simply `saul.pw/VisiData v2.5dev`

```
sheet	col	row	longname	input	keystrokes	comment
global		null_value	set-option			
			open-file	one	o	
one	com_istat		key-col		!	toggle current column as a key column
			open-file	two	o	open input in VisiData
two	cod_isat		key-col		!	toggle current column as a key column
two			sheets-stack		S	open Sheets Stack: join or jump between the active sheets on the current stack
sheets		キtwo	select-row		s	select current row
sheets		キone	select-row		s	select current row
sheets			join-sheets	inner	&	merge selected sheets with visible columns from all, keeping rows according to jointype
two+one	Denominazione		freq-col		F	open Frequency Table grouped on current column, with aggregations of other columns
result			rename-sheet	result		rename current sheet to input
result			save-sheet	result.tsv	^S	save current sheet to filename in format determined by extension (default .tsv)
```

**Comment by anjakefala** [comment] 2021-06-28 04:05
@aborruso I checked out the video!

I am so sorry, I reproduced, and the correct cmdlog is saved on my end. =( I suspect this is an environment issue, and that you have an old version of VisiData lying around somewhere. 

> How can i be sure that my VisiData version has the code changes you made? What file could I inspect?

You are right that this would be really useful information to be able to get within VisiData.

You could try `locate visidata` (if you are on Linux), to find the existence of every `visidata` file. You can also try repeatedly `pip3 uninstall visidata` and `sudo pip3 uninstall visidata`, and then trying your installation command again. You are right, that is the correct installation line.

**Closed as completed by anjakefala** 2021-06-28 04:05 UTC
Labels: bug

**Comment by aborruso** [comment] 2021-06-28 09:49
> You could try `locate visidata` (if you are on Linux), to find the existence of every `visidata` file. You can also try repeatedly `pip3 uninstall visidata` and `sudo pip3 uninstall visidata`, and then trying your installation command again. You are right, that is the correct installation line.

Done, and it works. Thank you very much
