### ISSUE TITLE
[windows] Highlight of row fails in ConEmu on WSL

### ISSUE THREAD

**Issue by mgaldzic** [saulpw/visidata#117] opened 2018-03-05 23:58 UTC
I use ConEmu as my terminal on WSL (Linux subsystem under windows 10)
The rows do not show the highlight to indicate the position.
The ConEmu task is set as:
set "PATH=%ConEmuBaseDirShort%\wsl;%PATH%" & ubuntu.exe -cur_console:pm:/mnt

![image](https://user-images.githubusercontent.com/406285/37006612-01125f22-208e-11e8-85f9-1dffafc9adf4.png)

**Comment by saulpw** [comment] 2018-03-06 01:15
Hi @mgaldzic, thanks for reporting this issue.  Unfortunately I don't ever use Windows, so I'm unable to diagnose and fix this issue.  (In fact I'm kind of surprised that it works at all!  You might be the first person to ever try using it on Windows).  If you are able to figure out what's going wrong, please let me know and we can try to find a solution.  You might start with the color options, and see if another curses attribute does something reasonable.

**Comment by Polydiac** [comment] 2018-03-06 20:41
@mgaldzic From what I have found out it has to do with WSL truncating the colour sequences for the console emulator ConEmu uses (WSL doesn't support 265 colours in ConEmu). There is a bridging script you can install that directly hooks into WSL which sort of works a bit better but still isn't great: [https://conemu.github.io/en/BashOnWindows.html#wslbridge](https://conemu.github.io/en/BashOnWindows.html#wslbridge)  @saulpw  Just out of interest for us Windows peasants. Have you considered supporting Windows with something like [https://pypi.python.org/pypi/UniCurses](https://pypi.python.org/pypi/UniCurses)? Would love to use this on windows natively.

**Comment by saulpw** [comment] 2018-03-08 04:10
Hi @Polydiac, I have to confess, I hadn't considered supporting Windows.  It would be difficult for me to do so because I don't even have it installed on any of my machines.  If there was enough interest I could hire someone to help make it happen (I know at least one Windows dev who would be interested).  But that costs money :/

**Comment by Polydiac** [comment] 2018-03-08 20:25
Yeah no worries. I know how hard windows support is for a primarily POSIX oriented Project. We can use it on WSL so it isn't that bad :D

**Comment by NicoJuicy** [comment] 2018-03-12 11:07
I actually also tried Windows, but was first demotivated when it didn't seem to support it on the main page. 

Since you're suprised it worked, i might suprise you more that Windows supports the entire Linux subsystem and command calls since recently.

Even Kali ( a linux distribution) is available on Windows : https://blogs.msdn.microsoft.com/commandline/2018/03/05/kali-linux-for-wsl/

So the support is pretty good :), i'd love to see Windows officially supported also.

**Comment by saulpw** [comment] 2018-03-19 08:00
Closing this for now, but if anyone in the future wants to put in the effort to support Windows more fully, let me know.

**Closed as completed by saulpw** 2018-03-19 08:00 UTC

**Comment by yab-arz** [comment] 2018-04-06 19:42
Just fyi, this issue appear to be fixed as of ConEmu 180318 Alpha which includes some fixes to console colors and reset codes.

**Comment by NicoJuicy** [comment] 2018-05-26 00:54
I can confirm everything seems to work on Windows Subsystem (y)
