### ISSUE TITLE
Improve User Experience of installing loader dependencies

### ISSUE THREAD

**Issue by snooppr** [saulpw/visidata#1765] opened 2023-02-27 04:52 UTC
The readme informs the user about a simple installation:
`pip3 install visidata`

The package is installed normally.  But when using for example (site that contains tables):
`vd url`  
the utility starts and displays one default tabular line instead of a table, confusing the user (this is not an error, as if the site simply does not have tables, or another table or something else).

I had to check the vd on several url(s) to understand that the vd was not working.

Since I'm using vd on an Android gadget/termux, the zoom didn't allow me to see the full message: a message that the "lxml" package is missing.
After installing the package "lxml" vd started working.
`pip3 install lxml`

Why doesn't vd install the dependencies it needs by default?  (lxml).  
The end user is a user, not a developer, he can't figure out why vd doesn't work out of the box.

**Update vd dependencies, add lxml package.**

**Comment by anjakefala** [comment] 2023-02-27 22:05
Duplicate of https://github.com/saulpw/visidata/issues/1739

**Comment by geekscrapy** [comment] 2023-03-01 05:52
I would like to generally suggest (as this has caught me out multiple times) that all deps for _any_ core feature (esp. if it is advertised on the website) is added to the requirements.txt.

A new user will click lots of things, open lots of files (this is a new tool to them, they should go wild) and it's discouraging for them to try and open something and it not work (esp. if they aren't terminal users and this is their first foray into the transition into gui+terminal tools), this is exponential if multiple things fail as they try to challenge vd more and more (they might ask the question, as old timers still do: what **_can't_** it open). This is probably also true for long term users (inc. myself). And this "it can open loads of formats" is one of the core draws to vd.

I'd love to just be able to say to a new user who may want to open XML "yup, just install visidata, and you're good to go". At the moment we have a multi step process: install visidata, try and open XML, it fails, try figure out why (which may not be obvious for a new py/terminal/pip user), install lxml, try again.

We have deps auto installed with plugins, so this should be the standard. I install vd and things that are included should just work. I understand the reason for keeping it light, but I feel there's a fine line between keeping it light and setting expectations. This expectation is set extremely high when there are loads of file formats shown (in the drop down) on the visidata home page, most of which can only be used once the file formats "process of elimination" has had its way with you 😅. I feel this would turn people off quite fast as they will find a tool that would work out of the box.

_(I appreciate this next comment refers to the dev branch, which may not automatically be part of a release, but it provides another example)_
The latest thing that caught me out was the inclusion of the menu item "zulip" (which if I'm honest is confusing why it is included by default)

**Comment by anjakefala** [comment] 2023-03-01 06:59
> I would like to generally suggest (as this has caught me out multiple times) that all deps for any core feature (esp. if it is advertised on the website) is added to the requirements.txt.

I am apologising because I have not had the capacity to read your full message. I have been procrastinating beginning my response to this issue because I am not sure how Saul feels about this issue, and what he thinks the best approach would be. But, I had a bit of a strong reaction because there is a requirements.txt in the repo, and I wanted to explain why we did not install everything in it by default.

I just wanted to clarify that we do list all of the dependencies for all of the loaders in the requirements.txt: https://github.com/saulpw/visidata/blob/develop/requirements.txt

It is very, very long. =( It will install a lot. And with pip if any dependency fails to install, VisiData fails to install. Our 3.11 build was red for a month because `h5py` and `arrow` did not have wheels built yet for Python 3.11. That would have effectively broken the VisiData install for Python 3.11. `arrow` might not be a core loader, but I think `.h5` is.

Once Saul moves in `vdsql`, that adds `ibis-framework` to the requirements.txt, and this is its requirements.txt: https://github.com/ibis-project/ibis/blob/master/requirements.txt.

This is a lot. This is way too much to install for every single person. I would really not be surprised if this turned a lot of people off of VisiData. "Why are you installing so much on my computer, if it will never be used?"

Some of our other packages, where it is a lot harder to install additional dependencies, address this by offering a tasting menu of what we believe would be the most popular loaders.

E.g. https://github.com/visidata/homebrew-vd/blob/master/Formula/visidata.rb
https://packages.debian.org/it/source/bullseye/visidata

And maybe it is time to do something similar for the pypi install. I agree that it is time to do something. There is understandable frustration and confusion with the current status. We could add some `extras` to setup.py for optional dependencies. `ibis-framework` does that. And it is absolutely time to have more helpful error messaging for what precisely people need to install to load the data they are interested in loading. Maybe, we have a sheet which lists all of the formats, and you press `a` to install any dependencies for that format. Or we create a VisiData[full] package for the wild ones who just want everything out of the box.

But, I did want to explain that we have been absolutely been maintaining a requirements.txt, and why, historically, we made the decision to not install everything listed in it.

**Comment by geekscrapy** [comment] 2023-03-01 07:13
Absolutely fine :) It didn't start out as a long message!

Thanks for the historic info, I think something that would go a long way is something like the plugin arch (of install and uninstall in `open-plugins`) would go a long way, except I can't think of an easy way to lead people there (esp. if they are new). I also know there was a decision made about having the loaders external (as plugins), and it didn't go that way.

It's a tough one, and I'm defo one of the people that doesn't want Hadoop or aws libs clogging my machine :D

Maybe a simple (?!) "fix", would be:
1. I open an xml file (without lxml installed)
2. I get a BIG popup telling me: "To open this, please click here to install the missing lib"
3. vd continues to open the file

With something like this, the user knows that it's the dep and it's not them doing something they shouldn't. Just a 2 second idea!

---
You slipped in some extra info :P

> Maybe, we have a sheet which lists all of the formats, and you press a to install any dependencies for that format

That would be nice too

**Comment by anjakefala** [comment] 2023-03-01 07:15
Yeah, these are all great!!

**Comment by saulpw** [comment] 2023-03-02 04:31
> The latest thing that caught me out was the inclusion of the menu item "zulip" (which if I'm honest is confusing why it is included by default)

This was an oversight; zulip commands should only be visible from Zulip sheets.  Will be fixed.

**Comment by anjakefala** [comment] 2023-03-04 00:39
> This was an oversight; zulip commands should only be visible from Zulip sheets. Will be fixed.

This was fixed!

**Comment by anjakefala** [comment] 2023-03-05 05:23
At minimum: I added nice error messages for as many modules as I could identify.

See here: https://github.com/saulpw/visidata/issues/1739

As I wrote in that issue, if I made a mistake or forgot something, please open a PR or let me know!

**Closed as completed** 2023-04-19 03:58 UTC
Labels: cosmetic
