### ISSUE TITLE
frequency histogram for number is wrong

### ISSUE THREAD

**Issue by setop** [saulpw/visidata#791] opened 2020-11-15 23:35 UTC
**Small description**

With [this data](https://github.com/saulpw/visidata/files/5543325/a.txt), when type casting year column to number `#`, and asking for frequency `F`, bins are wrong. I works correctly when not type casting.

**Expected result**

(obtained without type casting and moving 2020 to the top)

```
year	count	percent	histogram
2020	11	7.69	*********************************************
2019	12	8.39	**************************************************
2018	12	8.39	**************************************************
2017	12	8.39	**************************************************
2016	12	8.39	**************************************************
2015	12	8.39	**************************************************
2014	12	8.39	**************************************************
2013	12	8.39	**************************************************
2012	12	8.39	**************************************************
2011	12	8.39	**************************************************
2010	12	8.39	**************************************************
2009	12	8.39	**************************************************
```

**Actual result with screenshot**

(typecasting to number)

```
year	count	percent	histogram
2009	12	8.39	**************************
2010	12	8.39	**************************
2011	12	8.39	**************************
2012	12	8.39	**************************
2013	12	8.39	**************************
2014	12	8.39	**************************
2015	12	8.39	**************************
2016	12	8.39	**************************
2017	12	8.39	**************************
2018	12	8.39	**************************
2019	23	16.08	**************************************************
2020	0	0.00	
```

**Steps to reproduce with sample data and a .vd**

* [data](https://github.com/saulpw/visidata/files/5543325/a.txt)
* [commands](https://github.com/saulpw/visidata/files/5543339/a.vd.txt)

**Additional context**

version `saul.pw/VisiData v2.0.1`

it seems there is a limit to 11 bins and the rest is empty. The more I put data, the more is aggregated in the 11th bin.

**Comment by setop** [comment] 2020-11-23 20:39
Does anyone reproduce this bug ? It seems surprising for a such central feature ...

**Comment by anjakefala** [comment] 2020-11-23 21:50
Hi @setop!

What happens when you run this with `-g --numeric-binning=False`?

What happens if you run this with the branch off `develop` (while keeping numeric binning on)? It is possible that I have fixed this bug already on develop. 

Numeric binning is a relatively recent feature that still has some edge case kinks. We are debating keeping it off by default for this reason (the Frequency Table being so central).

If the problem is numeric binning, and this has not been fixed yet, your use case will be really useful for debugging this!

**Comment by anjakefala** [comment] 2020-11-24 01:01
I can confirm that this is a bug that is related to `numeric-binning` and is still relevant to `develop`. The current workaround for this dataset is to set `options.numeric_binning = False` in your `~/.visidatarc` or `-g --numeric-binning=False` on the commandline.

I will add it to my bug fixing queue.

**Comment by anjakefala** [comment] 2020-11-24 04:27
Thanks for the sample data! This should now be fixed on develop. =)

**Closed as completed by anjakefala** 2020-11-24 04:27 UTC
Labels: bug, fixed
