### ISSUE TITLE
[input] Persist input() history

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#736] opened 2020-10-18 15:31 UTC
There are multiple commands that ask for user input via input() and it's ilk.  It has a very powerful history feature, that has a concept of type.  This allows it to provide history in the right context.

It would be useful if VisiData could load and save history.  Even without save, load would be very useful.

It would be useful if the history file also could contain input-type information so that it is possible to load history for different input contexts.

**Comment by geekscrapy** [comment] 2020-10-18 16:01
I'll tag in this too. I'd love to be able to scroll through the history of past vd sessions. Helps when opening files of the same type one after another

**Comment by saulpw** [comment] 2020-10-27 19:30
Duplicate of #468.

**Closed as completed by saulpw** 2020-10-27 19:30 UTC
Labels: wishlist
