### ISSUE TITLE
Impossible to set current column for selected rows to incremental values and to bulk save all sheets

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#1339] opened 2022-03-25 17:27 UTC
**Small description**

Hi, I want to open and bulk save all the html tables I have [here](https://lab24.ilsole24ore.com/ecosistema-urbano/indexT.php). All the tables have the same name, then I need to rename them using `g+i`, and then save them in bulk `g+CTRL+s`.

When I run `g+i` I have `NameError: name 'setitem' is not defined`.

If I change the name of the tables, in the saved HTML files, when I run `g+CTRL+s`, I have `AttributeError: 'str' object has no attribute 'name'`

I start from 

```
 vd https://lab24.ilsole24ore.com/ecosistema-urbano/indexT.php --save-filetype=csv
```

**Expected result**

- to have the tables renamed;
- to be able to save the tables in multiple CSV files:

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/30607/160170624-208928a1-4e53-435f-bb63-77301335c5f3.png)

![image](https://user-images.githubusercontent.com/30607/160170720-c2696239-4cac-46dc-8dc0-f8aaa322fd5f.png)

![image](https://user-images.githubusercontent.com/30607/160170830-f81ef65c-3ac1-4e94-87b1-fb2204c5e685.png)

![image](https://user-images.githubusercontent.com/30607/160170866-f5c41e67-99f1-46f0-b920-e271251f9c4a.png)

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

```
sheet   col     row     longname        input   keystrokes      comment
global          null_value      set-option
global          save_filetype   set-option      csv
                        open-file       https://lab24.ilsole24ore.com/ecosistema-urbano/indexT.php      o
indexT                  select-rows             gs      select all rows
indexT  name            setcol-incr             gi      set current column for selected rows to incremental values
```

**Additional context**
Please include the version of VisiData: the latest dev saul.pw/VisiData v2.9dev

**Comment by frosencrantz** [comment] 2022-04-03 16:40
@aborruso This simple task uncovers multiple bugs in the code.  Thanks for the report!  Thank you @anjakefala  for fixing them!

**Comment by aborruso** [comment] 2022-04-03 16:42
> @aborruso This simple task uncovers multiple bugs in the code. Thanks for the report! Thank you @anjakefala for fixing them!

I'm very happy to be useful in some way. Thank you very much @anjakefala 

I can't wait for the PR to be approved and test it :)

**Comment by anjakefala** [comment] 2022-04-06 04:10
I think I fixed all of the issues that were rolled up in here! The fixes are on the `develop` branch, and will be part of the next release. =)

**Closed as completed by anjakefala** 2022-04-06 04:10 UTC
Labels: bug, fixed

**Comment by aborruso** [comment] 2022-04-06 06:18
> I think I fixed all of the issues that were rolled up in here! The fixes are on the `develop` branch, and will be part of the next release. =)

I have installed it running `pip3 install --upgrade --no-warn-script-location git+https://github.com/saulpw/visidata.git@develop`, but I have again `NameError: name 'setitem' is not defined`.

My vd file

```
sheet	col	row	longname	input	keystrokes	comment
global		null_value	set-option			
global		save_filetype	set-option	csv		
			open-file	https://lab24.ilsole24ore.com/ecosistema-urbano/indexT.php	o	
indexT			select-rows		gs	select all rows
indexT	name		setcol-incr		gi	set current column for selected rows to incremental values
```

Thank you @anjakefala

**Comment by anjakefala** [comment] 2022-04-06 15:07
Sorry. =( 

I am pretty sure this is again an issue where there is an older version of VisiData lying around that you need to find, and uninstall. I cannot reproduce. D=

**Comment by aborruso** [comment] 2022-04-06 15:20
> I am pretty sure this is again an issue where there is an older version of VisiData lying around that you need to find, and uninstall. I cannot reproduce. D=

I have uninstalled and than installed it again: now it works.

Thank you again

**Comment by frosencrantz** [comment] 2022-04-18 00:08
@anjakefala  thanks for your fixes! 

Later I realized my comment above (https://github.com/saulpw/visidata/issues/1339#issuecomment-1086904356 ) about this being a simple task is a good reason for simple tests for these fixes. So that future refactors don't break this code.  This didn't really come to me until after the fixes were committed.

It looks like this issue points out a problem with the Visidata tests, not all commands are tested. Bad references can exist in commands without notice.  I wonder if it would be useful to use something like pyp (https://github.com/hauntsaninja/pyp/issues/26)  to find  missing references as part of testing, so there would be a check for this  basic class of problem.  I think if tests reported this error, it might have helped prevent one of the issues.  Maybe a job for the someday list.

+@saulpw

**Comment by saulpw** [comment] 2022-05-01 03:58
We have https://github.com/saulpw/visidata/blob/stable/visidata/tests/test_commands.py, but they aren't working properly.  We should fix this and catch a lot of trivial bugs.  Thanks for the reminder, @frosencrantz.
