### ISSUE TITLE
Replaying a cmdlog where input is read from stdin fails

### ISSUE THREAD

**Issue by atarv** [saulpw/visidata#2582] opened 2024-10-22 13:25 UTC
**Small description**
I had written a script which got its input from stdin. It worked fine in v3.0.2, but with v3.1.1 it now fails with a "cannot open stdin when it is a tty" exception.

I traced the issue to these lines
https://github.com/saulpw/visidata/blob/2425a5fa3d9309338f7438c94c5f7002129f86e5/visidata/_open.py#L157-L159

Am I doing something wrong or is it supposed to work this way now?

**Data to reproduce**
Provided inline in next step.

**Steps to reproduce**
This is the minimal reproducible example I came up with.
```bash
echo -e '{"a":1}\n{"a":2}' | vd -f jsonl -p stdin.vdj --batch --debug -N
```
stdin.vdj has the following contents:
```jsonl
#!vd -p
{"sheet": "global", "col": null, "row": "regex_flags", "longname": "set-option", "input": "IS", "keystrokes": "", "comment": null, "replayable": null}
{"sheet": "global", "row": "filetype", "longname": "set-option", "input": "jsonl", "keystrokes": ""}
{"longname": "open-file", "input": "-", "keystrokes": "o", "replayable": true}
{"sheet": "-", "col": "", "row": "", "longname": "transpose", "input": "", "keystrokes": "Shift+T", "comment": "open new sheet with rows and columns transposed", "replayable": true}
```

**Expected result**
Input is read from stdin.

**Actual result with screenshot**

```
saul.pw/VisiData v3.1.1
opening stdin.vdj as vdj [visidata/_open.py:138:openPath]
finished loading stdin_vd [visidata/sheets.py:282:reload]
finished loading F6 [visidata/sheets.py:282:reload]
Your friend is your needs answered. [visidata/motd.py:30:domotd]
cannot open stdin when it is a tty [visidata/_open.py:159:openSource]
vd.push(openSource(inputFilename("open: "), create=True)) [visidata/basesheet.py:217:execCommand]
replay aborted during open-file [visidata/cmdlog.py:314:replayOne]
```

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?
  - yes

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?
  - latest release

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?
  - Linux, Ubuntu 23.04

- Which version of Python?
  - Python 3.11.4

- Which terminal are you using (for display and input issues)?
  - Alacritty

**Comment by midichef** [comment] 2024-10-22 19:35
You're not doing anything wrong. Apparently this is a bug I introduced in https://github.com/saulpw/visidata/pull/2442. The problem is an overly broad restriction on `open-file` with an input of `"-"`.

I'll look into a fix ASAP.

For now, if you want to stay with v3.1.1 you can try commenting out the `open-file` line in your .vdj:

```
{"longname": "open-file", "input": "-", "keystrokes": "o", "replayable": true}
```

I think that line is unnecessary, at least for this example.

If changing your cmdlog files is not feasible, you can leave your .vdj files as is, and wait for a patch. Keeping existing cmdlogs working is a high priority, so the next patch won't break them.

I think there is a fix for this bug, while still addressing the terminal lockup problems in #2442, but I'll know more after I test it today.

**Closed as completed** 2024-11-09 03:52 UTC
Labels: bug
