### ISSUE TITLE
Menu rendering issue in kitty terminal

### ISSUE THREAD

**Issue by dolmen** [saulpw/visidata#1628] opened 2022-12-20 16:56 UTC
**Small description**

Using Visidata v2.8 from [kitty](https://sw.kovidgoyal.net/kitty/) 0.26.3 on macOS Monterey (12.6).

See screenshot of bad rendering of menus.
<img width="1668" alt="Capture d’écran 2022-12-20 à 17 47 22" src="https://user-images.githubusercontent.com/129536/208722074-ebe40a5f-edf6-460e-b876-9a48f27a79db.png">

**Expected result**

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
1. Open Kitty 0.26.3
2. Open the Hanukkah of Data DB with VisiData: `vd noah.sqlite` from the shell in Kitty
3. Open the file menu
4. Navigate menu items

**Additional context**
Visidata v2.8
Kitty: https://sw.kovidgoyal.net/kitty/

**Comment by anjakefala** [comment] 2023-04-22 04:02
Hi @dolmen!

This is a duplicate of https://github.com/saulpw/visidata/issues/1259. Can you please go to that issue, and see if the suggestions solve your problem?

It seems like folks needed to set the TERM=xterm or TERM=xterm-256color. If none of that works for you, I would encourage you to participate in that thread. I will pin it so anyone running into render issues can find it.

**Closed as completed by anjakefala** 2023-04-22 04:02 UTC
Labels: bug
