### ISSUE TITLE
Cursor jumps upwards from final visible row after moving down a row

### ISSUE THREAD

**Issue by uoee** [saulpw/visidata#832] opened 2020-12-08 20:16 UTC
Commit c9e8f5ed introduced a jarring cursor movement where the cursor hops between the last and second last row when pressing the key to move downwards (moving upwards is fine).

I think it's just an off by one error. Briefly looking myself, the issue is (at least superficially) solved by subtracting 1 from `self.bottomRowIndex` in https://github.com/saulpw/visidata/blob/c9e8f5edc5044293ca4931de3d976ef10d8e2907/visidata/sheets.py#L551

    self.bottomRowIndex = self.cursorRowIndex - 1

However, this is not tested (other than no crashes so far), and I'm not remotely familiar with the codebase, so this may affect something else I'm unaware of.

**Comment by anjakefala** [comment] 2020-12-08 20:25
Hey @uoee, thanks for making an issue. 

I agree that is disconcerting behaviour. I unfortunately cannot reproduce it. =( 

Could you please give more environment information, like your shell and terminal? Are you using tmate? Which VisiData loader are you using? Is this in single-line mode or multi-line mode? A gif would be helpful; if you are on Linux, you can use Peek to make one.

**Comment by anjakefala** [comment] 2020-12-08 20:36
Ah, never mind, I understand what is happening now. Thanks!

**Comment by anjakefala** [comment] 2020-12-08 20:39
Current behaviour

![Peek 2020-12-08 12-37](https://user-images.githubusercontent.com/7489659/101538662-4acd4480-3952-11eb-9ce5-08d1dba520b5.gif)

Previous behaviour

![Peek 2020-12-08 12-38](https://user-images.githubusercontent.com/7489659/101538685-54ef4300-3952-11eb-8e3f-1a75f8525e0c.gif)

**Comment by saulpw** [comment] 2020-12-09 05:50
Yes, that is annoying.  The solution is trickier than that, unfortunately, as this code also has to deal with scrolling multi-line rows properly (and the bug it fixes is worse, even if multiline usage is less common).  We'll look into it and come up with some more workable solution.

**Comment by anjakefala** [comment] 2020-12-09 06:52
Hi @uoee! 

A fix was merged to `develop`. Please give it a whirl! 

This will be part of the next release. Again, thanks so much for submitting an issue on this.

**Closed as completed by anjakefala** 2020-12-09 06:52 UTC
Labels: bug, fixed
