### ISSUE TITLE
Input lag moving between lines and columns

### ISSUE THREAD

**Issue by robertdefilippi** [saulpw/visidata#1168] opened 2021-11-03 15:32 UTC
**Small description**
When scrolling through rows and columns, if I move more than a few columns or rows at a time (maybe 5 or more) there is a lag after I release the keys and the on screen selection continues to move as if it is still collecting commands from the keyboard.

**Expected result**
When the keys on the keyboard are released, the selection movement also stops.

**Actual result with screenshot**

Not an error message, but this is what I get when calling CRTL + E

![image](https://user-images.githubusercontent.com/9288605/140090778-d1f42876-034c-4d16-a78c-ea08ee17b217.png)

**Steps to reproduce with sample data and a .vd**

Maybe this is part of the issue, as then I try to get the command log it says I have no keystrokes even after moving around the file.

![image](https://user-images.githubusercontent.com/9288605/140091679-1b36cf5a-7fd3-4c66-bd5f-a71c8e2c01a3.png)

**Additional context**

```
❯ vd -v
saul.pw/VisiData v2.6.1
```

Would love to help debug this if possible!

Thank you!

**Comment by anjakefala** [comment] 2021-11-06 05:34
Hi @robertdefilippi! Thanks for filing an issue.

Unfortunately, I cannot reproduce, and need some more information from you!

How big is the file you are scrolling?
How big is your terminal screen?
Which operating system platform are you on?

In terms of the error message you are seeing, that is related to https://github.com/saulpw/visidata/issues/1131, and will be fixed next release. =)

> Maybe this is part of the issue, as then I try to get the command log it says I have no keystrokes even after moving around the file.

We do not actually log cursor movement in the *CommandLog*! It is not necessary because we log the context for the commands in `sheet`, `row`, `column`. So their absense is expected. =)

**Comment by saulpw** [comment] 2021-11-09 02:54
Closed pending further information.

**Closed as completed by saulpw** 2021-11-09 02:54 UTC
Labels: bug
