### ISSUE TITLE
Unable to select data points in plot using the alacritty terminal

### ISSUE THREAD

**Issue by zakora** [saulpw/visidata#203] opened 2018-11-02 08:54 UTC
Hi,

When using the [alacritty](https://github.com/jwilm/alacritty) terminal, I can't select data points with the "left click & drag" method. When using other terminals such as Gnome Terminal or Kitty it works fine.

This issue is probably due to alacritty, but I wanted to post here to understand what could cause this behavior.
Could you point me to how the "left click & drag" selection is handled in visidata?
Then I will be able to explain the bug in another issue that I will make on the alacritty project.

Here is a screen capture where I try to select data points without success: [screen_capture.zip](https://github.com/saulpw/visidata/files/2541602/screen_capture.zip)
We can see "no command for ..." appearing multiple times at the bottom of the screen.

Thanks

**Comment by saulpw** [comment] 2018-11-03 02:40
Hi @zakora,

The code for these are in [canvas.py](https://github.com/saulpw/visidata/blob/stable/visidata/canvas.py#L653) (`BUTTON1` is left-click, `BUTTON3` is right-click).  In your video, I notice that we don't see anything like `BUTTON1_PRESSED` when you press the left button. Instead, there are many keypresses in a short period of time, including (very briefly) `^[` (ESC), which indicates that alacritty is sending ANSI-style escape sequences for mouse events, which are not being properly interpreted.  Likely causes are either an incorrect terminfo for alacritty (which might be fixed by setting `TERM` to a different value), or perhaps the timing of the escape sequence is slow because alacritty is set to an artificially low baudrate.

When you find the cause issue (or any clue), please post it here so we can either improve VisiData or help the next person who comes along.  Thanks for reporting it!

**Closed as completed** 2018-11-03 02:40 UTC

**Comment by zakora** [comment] 2018-11-05 08:28
Thanks for your answer @saulpw , I was able to track down the cause of the bug. In the end, it came down to me not properly compiling the terminfo file for alacritty.

Here is an explanation of the bug for future reference.
First, I made minimal python script to test if the mouse events are handled correctly, it uses the python `curses` library, like visidata:

```python
import curses

def main(scr):
    curses.mousemask(curses.ALL_MOUSE_EVENTS)
    extra_info = ""
    
    while True:
        key = scr.get_wch()

        if key:
            if key == curses.KEY_MOUSE:
                mouse_info = curses.getmouse()
                extra_info = "extras: {}".format(mouse_info)
                
            key = ord(key) if isinstance(key, str) else key
            name = curses.keyname(key).decode('utf-8')
            scr.addstr("got: {}. {}\n".format(name, extra_info))

            extra_info = ""

if __name__ == '__main__':
    curses.wrapper(main)
```
When clicking, a correct terminal outputs:
![gh_alacritty4](https://user-images.githubusercontent.com/106620/47986003-afff3d80-e0db-11e8-9866-039016a0fc3c.png)

A faulty terminal, like I had, outputs gibberish, including the `^[` escape character:
![gh_alacritty2](https://user-images.githubusercontent.com/106620/47986037-ca391b80-e0db-11e8-85c6-6092e24b5be9.png)

Thanks to your comment about a possible incorrect terminfo for alacritty, I remembered that I saw some  warnings when I compiled the terminfo for alacritty with `tic -e`. Messages like:
`"alacritty.info", line 17, col 8, terminal 'alacritty-direct': unknown capability 'RGB'`
So I did `tic -x -e …` to suppress the warnings, thinking that no more of these messages was a good thing. After searching online, I found an [issue](https://github.com/jwilm/alacritty/issues/1633) related to these warnings, and a developer mentions that this tic messages are not to be considered relevant. He also provided [a more detailed explanation](https://github.com/jwilm/alacritty/issues/1633#issuecomment-435699816).

Finally, to fix my bug, I just had to compile the alacritty terminfo with `tic -e …` instead of `tic -x -e …`.
