### ISSUE TITLE
Look for .visidatarc in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by mjkalyan** [saulpw/visidata#980] opened 2021-05-13 05:32 UTC
Probably a lot the main demographic for this type of software would prefer to keep their config files in either the default `XDG_CONFIG_HOME` (`~/.config`) or another directory pointed to by this variable. I'm certain there are python libraries to search for the right config directory based on the XDG specification, with fall-backs and all. The same goes for `~/.visidata/cache` which should go in `$XDG_CACHE_HOME/visidata` (falling back on `~/.cache/visidata`).

**Comment by saulpw** [comment] 2021-05-16 02:01
Hi @mjkalyan, thanks for the suggestion.  This has been on our radar and is a duplicate of #487.  I'm open to it if someone wants to submit a PR or sponsor the bug, but I'm not willing to take a dependency for it, and it's more complicated than I'm motivated to implement right now.

Kondo'ed for now.

**Closed as completed by saulpw** 2021-05-16 02:01 UTC
Labels: wishlist
