### ISSUE TITLE
unable to open a CVS using pipe as delimiter

### ISSUE THREAD

**Issue by verajosemanuel** [saulpw/visidata#481] opened 2020-03-06 13:35 UTC
**Small description**
unable to open CSV using pipe as delimiter

**sample file**
```
SPEED|START|END|RSYNC|SIZE
normal|2019/12/23 23:00:01|2019/12/23 23:00:33|2019/12/23 23:00:42|96M  total
high|2019/12/21 21:01:01|2019/12/21 21:01:44|2019/12/21 22:51:32|19M    total
low|2019/12/22 02:00:01|2019/12/22 06:26:08|2019/12/22 09:11:44|40G total
normal|2019/12/22 21:01:01|2019/12/22 21:01:44|2019/12/22 22:55:58|19M  total
high|2019/12/23 02:00:01|2019/12/23 06:26:53|2019/12/23 09:13:01|40G    total
low|2019/12/23 21:01:01|2019/12/23 21:01:44|2019/12/23 21:03:06|20M total
normal|2019/12/23 22:00:01|2019/12/23 22:01:13|2019/12/23 22:49:32|64M  total
high|2019/12/24 00:01:01|2019/12/24 04:04:19|2019/12/24 04:34:28|66G    total
low|2019/12/24 05:00:01|2019/12/24 06:00:34|2019/12/24 06:52:03|9.0G    total
normal|2019/12/24 02:00:01|2019/12/24 06:30:49|2019/12/24 09:19:59|40G  total
low|2019/12/24 04:00:01|2019/12/24 07:23:50|2019/12/24 13:50:29|16G total
```

**command**
 ```
 vd --csv-delimiter '|' global.csv # or
 vd --csv-delimiter='|' global.csv
```
**obtained result**
![visi1](https://user-images.githubusercontent.com/15836677/76088109-c2330980-5fb7-11ea-898c-691c4857e8e0.png)

**Comment by ajkerrigan** [comment] 2020-03-06 14:01
Hey @verajosemanuel - thanks for providing sample input, your command and a screenshot! Out of curiosity which version of VisiData are you using though? I've tried reproducing this with the latest stable release (v1.5.2) and the current `develop` branch, and in both cases I get this:

```
 SPEED  | START              | END                | RSYNC              | SIZE          ║                              
 normal | 2019/12/23 23:00:01| 2019/12/23 23:00:33| 2019/12/23 23:00:42| 96M  total    ║
 high   | 2019/12/21 21:01:01| 2019/12/21 21:01:44| 2019/12/21 22:51:32| 19M    total  ║
 low    | 2019/12/22 02:00:01| 2019/12/22 06:26:08| 2019/12/22 09:11:44| 40G total     ║
 normal | 2019/12/22 21:01:01| 2019/12/22 21:01:44| 2019/12/22 22:55:58| 19M  total    ║
 high   | 2019/12/23 02:00:01| 2019/12/23 06:26:53| 2019/12/23 09:13:01| 40G    total  ║
 low    | 2019/12/23 21:01:01| 2019/12/23 21:01:44| 2019/12/23 21:03:06| 20M total     ║
 normal | 2019/12/23 22:00:01| 2019/12/23 22:01:13| 2019/12/23 22:49:32| 64M  total    ║
 high   | 2019/12/24 00:01:01| 2019/12/24 04:04:19| 2019/12/24 04:34:28| 66G    total  ║
 low    | 2019/12/24 05:00:01| 2019/12/24 06:00:34| 2019/12/24 06:52:03| 9.0G    total ║
 normal | 2019/12/24 02:00:01| 2019/12/24 06:30:49| 2019/12/24 09:19:59| 40G  total    ║
 low    | 2019/12/24 04:00:01| 2019/12/24 07:23:50| 2019/12/24 13:50:29| 16G total     ║
```

**Comment by verajosemanuel** [comment] 2020-03-07 09:48
saul.pw/VisiData v1.5.2

**Comment by ajkerrigan** [comment] 2020-03-07 12:54
Ok thanks. I'm not sure what's going on, but there are some things we can try to help track it down:

* Try running with `vd --csv-delimiter='|' -f csv global.csv` to be sure that vd isn't accidentally using a different loader for some reason.

* After you open the file, check and share the info from status history (`^P`). There should be a version line and then a few status messages, including something like "opening global as csv". But there may be other messages that help point to the problem.

* Check the error log (`^E`) to see if there are any error messages and tracebacks there.

* To really focus on the `|` character, try replacing that character in that file and see if you get the same results. Something like:

```bash
sed s/\|/,/g global.csv | vd -f csv
```

Hopefully one of those steps will turn up something useful!

**Comment by verajosemanuel** [comment] 2020-03-09 08:47
^P
![error](https://user-images.githubusercontent.com/15836677/76196520-a9f70080-61ea-11ea-961f-526ad040f07d.png)

^E
No error

sed s/\|/,/g global.csv | vd -f csv

![noerror](https://user-images.githubusercontent.com/15836677/76196736-0c500100-61eb-11ea-801d-d4fe99f0efdf.png)

**Comment by ajkerrigan** [comment] 2020-03-09 16:06
Thanks, unfortunately I'm not sure where to go from there. Those tests confirm that VisiData is using the CSV loader, and seem to rule out some edge case "similar-looking character" issues. One remaining thing I can think to check is trying to pipe the file to vd rather than reading it directly:

```bash
< global.csv | vd --csv-delimiter "|" -f csv
```

That would help highlight a file format/encoding issue, which the `sed` test may have worked around. Aside from that, I'm out of ideas since I can't reproduce the issue.

**Comment by saulpw** [comment] 2020-03-09 16:16
@verajosemanuel what platform/shell are you using?

**Comment by verajosemanuel** [comment] 2020-03-09 16:23
Ubuntu Eoan. Zsh

**Comment by anjakefala** [comment] 2020-03-09 18:05
Am I missing something or does @verajosemanuel VisiData screen after the sed look like expected?

**Comment by anjakefala** [comment] 2020-03-09 18:06
I was missing something, nvm!

**Comment by anjakefala** [comment] 2020-03-14 16:44
@verajosemanuel, I am going to close this issue soon due to lack of reproducibility/activity! @ajkerrigan, you made a heroic attempt to try to debug it.

**Closed as completed** 2020-03-16 04:15 UTC
Labels: bug
