### ISSUE TITLE
if a filename is edited, it extension will miss in filename column.

### ISSUE THREAD

**Issue by Freed-Wu** [saulpw/visidata#1796] opened 2023-03-09 12:43 UTC
**Small description**
if a filename is edited, it extension will miss in filename column.

**Steps to reproduce with sample data and a .vd**
```sh
$ cd /dev/shm
$ touch a.txt c.txt d.txt
$ vd -N
```

Press `le<C-e><C-u>b.txt<CR>`

**Expected result**

Display `b.txt` in filename

**Actual result with screenshot**
Display `b` in filename

**Comment by anjakefala** [comment] 2023-03-22 03:26
Hey @Freed-Wu!

Which version of VisiData are you on? I was unable to reproduce:

![Peek 2023-03-21 20-24](https://user-images.githubusercontent.com/7489659/226794400-45020230-833d-4f96-9244-427800f11b6f.gif)

We did have some bugfixes for **DirSheet** in v2.11. If you are on v2.11 or later, could you try recording a gif, or taking screenshots, to show me what you are seeing?

**Comment by Freed-Wu** [comment] 2023-03-22 06:01
Here is gif: <https://asciinema.org/a/DjPvsV6SfBRGw4Fj0QDk7kdeL>
I use v2.11.

**Comment by anjakefala** [comment] 2023-03-28 05:07
Great! Good news. =) This has been fixed in the `develop` branch; which is why I could not reproduce it. This will be in the next release.

**Closed as completed by anjakefala** 2023-03-28 05:07 UTC
Labels: bug, fixed
