### ISSUE TITLE
First row in the All Sheets Sheet is not sorted.

### ISSUE THREAD

**Issue by franzhuang** [saulpw/visidata#1620] opened 2022-12-06 22:05 UTC
**Small description**
First row is not  sorted with [  or  ]  in columns of Sheets Sheet.

**Expected result**
All rows should be sorted in Sheets Sheet.

**Actual result with screenshot( sort in nRows columns)**
![222127624](https://user-images.githubusercontent.com/87310483/206032798-d8fbb524-6556-4493-b2a5-44826ef840b5.png)
![22212755939](https://user-images.githubusercontent.com/87310483/206032868-f61822d8-763f-4c2b-ad0f-b41d47e9bde2.png)

**Steps to reproduce with sample data and a .vd**
1. open several files.
2. press shift + S to open Sheets Sheet.
3. go to nRows or nCols or other numeric columns, and type [  or  ] to sort.

**Additional context**
Version 2.10.2

**Comment by saulpw** [comment] 2022-12-06 22:15
This is actually by design on the Sheets Sheet, since the first sheet is the current/top sheet, so sorting the list of sheets would surprisingly change the current sheet. The issue that you reported on reddit, is that the global Sheets Sheet has the same behavior, even though its first sheet is not the top sheet.

**Comment by franzhuang** [comment] 2022-12-06 23:11
Sure , I have to moodify my report as follows:

**Small description**
First row is not  sorted with [  or  ]  in columns of  ***global*** Sheets Sheet.

**Expected result**
All rows should be sorted in ***global*** Sheets Sheet.

**Actual result with screenshot( sort in nRows columns)**
![2221277857](https://user-images.githubusercontent.com/87310483/206044802-bc59c92c-e55c-4c5f-add2-22daeab127ba.png)
![2221277839](https://user-images.githubusercontent.com/87310483/206044804-65cc9738-3bd2-404a-893f-a26108f1b2ad.png)

**Steps to reproduce with sample data and a .vd**
1. open several files.
2. press ` g  shift + S` to open ***global*** Sheets Sheet.
3. go to nRows or nCols or other numeric columns, and type [  or  ] to sort.

**Additional context**
Version 2.10.2

**Comment by anjakefala** [comment] 2023-01-03 05:41
Thanks for letting us know @franzhuang! This should now be fixed on `develop`.

**Closed as completed** 2023-01-03 05:41 UTC
Labels: bug, fixed
