### ISSUE TITLE
Attempting to undo a failed cast causes indefinite hang

### ISSUE THREAD

**Issue by lxcode** [saulpw/visidata#794] opened 2020-11-18 21:50 UTC
**Small description**

If you do a goofy cast, like hit $ on a date, hitting U afterward causes visidata to lock up indefinitely, consuming 100% of a CPU/core.

**Expected result**

Clear the "!" error markers maybe? Or just do nothing.

**Steps to reproduce with sample data and a .vd**

Should work with anything, but here's a freq analysis that I tested it on. Cast the date as $ and then U.

[test.csv.txt](https://github.com/saulpw/visidata/files/5562934/test.csv.txt)

**Additional context**
macOS 11, Python 3.9, 2.0.1

**Comment by anjakefala** [comment] 2020-11-18 22:29
Hi @lxcode!

Nice timing. =) I just fixed this on develop recently. https://github.com/saulpw/visidata/commit/411de01ecfa9b6393df437449d8fc0aa800742eb

It will be in the next release.

**Comment by geekscrapy** [comment] 2020-12-01 12:11
I'm actually still getting this issue with a CSV sheet, JSON worked fine! Pulled the latest commit and ran with (only change is the `-f ...`):

**works fine**
`PYTHONPATH=. python visidata_upstream/bin/vd -f jsonl https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/nginx_json_logs/nginx_json_logs --config='/dev/null'`

**fails (I appreciate its not a valid csv but it fails the same even with a valid file)**
`PYTHONPATH=. python visidata_upstream/bin/vd -f csv https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/nginx_json_logs/nginx_json_logs --config='/dev/null'`

**Comment by anjakefala** [comment] 2020-12-01 17:50
Closed @geekscrapy , because I was unable to reproduce! Let's follow this up in #visidata on Freenode.

**Closed as completed by anjakefala** 2020-12-01 17:50 UTC
Labels: bug, fixed
