### ISSUE TITLE
Feature request: Allow guessing column types

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1639] opened 2022-12-27 10:23 UTC
I like that VisiData lets me decide which columns are integers, floats, dates etc. But most of the time, I wouldn't like to do the manual work of marking these columns as such. I'd like to have a command that automatically guesses the column types based on some heuristics. It doesn't need to be perfect.

**Comment by saulpw** [comment] 2023-10-25 01:28
This is a duplicate of #349, which already has some useful code snippets.  @cool-RR, I think you've made your own column-type-guessing function since you posted this issue; maybe you could post it into #349 as well?  If we decide to incorporate this functionality into stock VisiData it would be useful to have it all in one place.

**Closed as not planned by saulpw** 2023-10-25 01:28 UTC
Labels: wishlist
