### ISSUE TITLE
"awk" like key/value loader (and output)

### ISSUE THREAD

**Issue by fourjay** [saulpw/visidata#1179] opened 2021-11-07 21:14 UTC
Just discovered visidata  (it's very cool, thank you).
I expected, but could not find a loader for the quintessential "awk" like format:
* key/val (often colon separated)
* one field per line
* records separated by blank line.

This is a classic unix format. Was able to get something working with miller (also a new tool for me) and of course I could do an awk one-liner. But it seems like something visidata should support directly. I can probably write a loader for this (my python is not great, but it seems straightforward enough).

Sample use case, using ldapsearch to output a set of users and viewing the results as a table.
As indicated above, I used miller to build a pipeline, and am pleased with the end result (it's somewhat of a revelation to explore the data for anomalies without a specific concern).

On a related note, sort of a "preferred/expected behaviour". In the above pipeline I used a JSON export.
I noticed that a row detail view for JSON  shows two columns, key and value
But the equivalent CSV detail view just shows vertical field list.
I'd expect (and would like) the row detail view to display the field header
(for many columns, this helps visualize fields)

Again, thanks for the very cool tool

**Comment by saulpw** [comment] 2021-11-07 21:51
Hi @fourjay, thanks, this is a good suggestion.  I agree, it should be easy enough to add a loader; it sounds similar to the `rec` (recutils) filetype.

Your second request is a duplicate of #1172, and I think that'll be implemented sometime soon.

I'm also really glad to hear this:

> it's somewhat of a revelation to explore the data for anomalies without a specific concern

If I have an overarching mission with my work, it's to promote the value of undirected exploration.  You never know what "unknown unknowns" might be lurking in any dataset!

**Comment by saulpw** [comment] 2021-11-09 04:54
It's such a simple format that it was kind of fun to implement.  What's the best filetype for the format?  Right now it's `awk` but I believe files with extension `.awk` are actually awk scripts, not data.

Also, can multiple sheets be in one file?

**Closed as completed** 2021-11-09 04:55 UTC
Labels: wishlist, wish granted

**Comment by fourjay** [comment] 2021-11-09 17:35
> What's the best filetype for the format?
I'd suggest ".lsv" - for "line separated values"
There ought to be a name for it, but I don't know of any.
".awk" is a pretty standard extension for awk files (of course).
I only mentioned awk, as it has special support for this format.
Idiomatically 'BEGIN {FS="\n"; RS="";}'
The RS value is shorthand for "\n\"

More accurately, it's an "exploded" CSV :-)
An early "structured data" precursor to XML/YAML
