### ISSUE TITLE
[v2.9dev] Ctrl-Y fails to open a sheet larger than 1x1

### ISSUE THREAD

**Issue by Gurkenglas** [saulpw/visidata#1303] opened 2022-02-25 23:43 UTC
![Screenshot from 2022-02-26 00-38-26](https://user-images.githubusercontent.com/1489801/155817355-f8963f14-4d48-4a8f-a290-a8430f80f25c.png)
[ctrlyfail.json.txt](https://github.com/saulpw/visidata/files/8145423/ctrlyfail.json.txt)
[ctrlyfail[][0].vd.txt](https://github.com/saulpw/visidata/files/8145424/ctrlyfail.0.vd.txt)

**Comment by anjakefala** [comment] 2022-02-26 05:03
Thanks for the sample file! I was successfully able to reproduce the issue. I do not think it has to do with the Sheet size (I failed to reproduce the issue with a similar workflow with different data).

I will try to narrow in on what the problem is. My current hint is that the type of the `cursorRow` that `pyobj-row` is getting is `str` with this sample data. It usually gets a different sort of object (e.g. `Column` or `List`).

**Comment by Gurkenglas** [comment] 2022-02-27 12:59
gCtrl-E should log type mismatches that visidata had to address, then!

**Comment by anjakefala** [comment] 2022-03-06 07:32
`Enter` is producing a `SheetDict`, since the rows of a json object are dictionaries.. This is the template for a `SheetDict`:

```
 # source is dict                                                                                                                                                                                   
 class SheetDict(PythonSheet):                                                                                                                                                                      
     rowtype = 'items'  # rowdef: keys                                                                                                                                                              
     columns = [                                                                                                                                                                                    
         Column('key'),                                                                                                                                                                             
         Column('value', getter=lambda c,r: c.sheet.source[r],                                                                                                                                      
                         setter=lambda c,r,v: setitem(c.sheet.source, r, v)),                                                                                                                       
     ]                                                                                                                                                                                              
     nKeys = 1                                                                                                                                                                                      
     def reload(self):                                                                                                                                                                              
         self.rows = list(self.source.keys())                                                                                                                                                       
                                                                                                                                                                                                    
     def openRow(self, row):                                                                                                                                                                        
         return PyobjSheet(self.name, row, source=self.source[row])
```

So, each individual row is the key value (a string) for that particular row. That is why `Ctrl+Y` is returning a `TextSheet` for the key value on a `SheetDict`. So, this can be best described as `Ctrl+Y` is showing an un-intuitive result for `SheetDict`s.

**Comment by anjakefala** [comment] 2022-03-16 03:48
Closing this because `Ctrl+Y` is doing its intended behaviour: it is showing the contents of the current row. 

I could see a change to preload all of the `PyobjSheet`s for each of the keys to be the actual `rows`, in which case `Ctrl+Y` would be equivalent to `Enter`. This could become heavy for large dictionaries, and seems wasteful considering that `Enter` already exists to open them (`Enter` calls the `openRow`). 

I will incorporate this into the documentation when I work on documentation for `PyobjSheet`! Thanks for telling me about this. =)

**Closed as completed by anjakefala** 2022-03-16 03:48 UTC
Labels: By Design
