### ISSUE TITLE
[macros] Macros/Macros sheet loading is broken

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2142] opened 2023-11-27 21:47 UTC
**Small description**
Macro sheet loading is broken.  Macros sheet is broken

**Expected result**
Macros are loaded, can view macros sheet. Can run macros

**Actual result with screenshot**
https://asciinema.org/a/iGGChydw6UZHasKNDmIbFDX34

**Steps to reproduce with sample data and a .vd**

Try to use an existing macro, they don't exist.
Go to macros sheet `gm`, it is empty even if you have macros.

**Additional context**
Please include the version of VisiData and Python. latest develop b7901d99. Python 3.9.2

**Comment by saulpw** [comment] 2023-11-27 22:08
Okay, so we've made a new, more-generalized mechanism for persisting data, which stores the macro index in a different way than the old `macros.tsv` file.  To convert:

    vd -b -o ~/.visidata/macros_list.json ~/.visidata/macros.tsv

I think your old macros should work fine after that.  Sorry for not messaging this properly; how do you think we should inform existing users of this before they panic about losing their macros?

**Comment by frosencrantz** [comment] 2023-11-28 19:40
I don't have a great answer.  It cneeds to be mentioned in the changelog. 

To me I guess there are some additional options:
- Just convert it automatically, and add a note in the status messages that it was done.
   - If there is an error, like it is not able to write the new json, then report that and give a link to how to fix it.
- Add notes in the status message saying the old version is exists along with simple instructions to fix with a link for more details.

Not sure if it is useful to have an option to stop this behavior, for someone who is using the old and new versions.

I think I would just convert it, with care for the failure case.

**Comment by frosencrantz** [comment] 2023-11-28 19:45
Maybe I should create a new issue.  I realized that input history has been removed.  Nooooo.... 

Maybe I misunderstand what is happening. That holds a lot of useful history.  

Earlier I was trying to reuse capture regex, gone.  If I realize I made a mistake, I need to retype the whole thing.  What is replacing the input history or what is it's new form?

**Comment by frosencrantz** [comment] 2023-11-29 21:56
@saulpw how are stored properties suppose to work?  It looks like there is a way for the contents to be saved to a json file, but it is not happening in my environments.  Is there some sort configuration that needs to be specified?

**Comment by saulpw** [comment] 2023-11-29 22:14
Hi @frosencrantz, they will be saved, it's a bug, I have a fix locally that I'll push hopefully tonight.  The issue is that vd calls `os._exit` at the end to avoid the cleanup time, but that also means the `atexit` savers aren't getting called.  Don't worry, we're not getting rid of the input history :)

**Comment by frosencrantz** [comment] 2023-12-05 22:47
@saulpw  I think this code is still broken.  If you are running multiple VisiData commands and separate terminals, it seems like the history of the command that finishes second will overwrite any changes of the one that finishes first.  I haven't tried to debug this yet, but history is being lost.

**Comment by saulpw** [comment] 2023-12-05 23:30
Brilliant, thank you @frosencrantz.  I knew there was some problem with structuring it this way.  I'll see how I can fix it.

**Comment by frosencrantz** [comment] 2023-12-06 23:54
I think related is that creating new macros is having a problem, but this will likely be in a update you are working on:

 https://asciinema.org/a/o99yumgv5xGQMUlPRhMHdCuxu

```
Traceback (most recent call last):
File "usr/lib/python3.9/site-packages/visidata/basesheet.py", line 208, in execCommand
escaped = super().execCommand2(cmd, vdglobals=vdglobals)
File "usr/lib/python3.9/site-packages/visidata/extensible.py", line 79, in wrappedfunc
r = oldfunc(*args, **kwargs)
File "usr/lib/python3.9/site-packages/visidata/basesheet.py", line 73, in execCommand2
exec(code, vdglobals, LazyChainMap(vd, self))
File "macro-record", line 1, in <module>
'VisiData: a curses interface for exploring and arranging tabular data'
File "usr/lib/python3.9/site-packages/visidata/macros.py", line 120, in startMacro
vd.cmdlog.saveMacro(vd.macroMode.rows, ks)
File "usr/lib/python3.9/site-packages/visidata/macros.py", line 92, in saveMacro
vd.sync(vd.macrosheet.source.reload())
AttributeError: 'dict' object has no attribute 'reload'
```

**Comment by frosencrantz** [comment] 2023-12-13 21:36
I'll add two more data points:
 - When quiting it looks VisiData always saves over the files like macros_list.json, even if it has not changed in that process.
 - Before this update, VisiData input history worked well with multiple parallel VisiData processes

**Comment by anjakefala** [comment] 2023-12-21 06:57
Hey @frosencrantz, I added a `dev/port-macros.vdj` file! https://github.com/saulpw/visidata/blob/develop/dev/port-macros.vdj

Porting your macros should be as simple as `vd -p dev/port-macros.vdj`. Could you try it out?

**Comment by saulpw** [comment] 2023-12-22 00:01
I believe this should be fixed now, and the .vdj @anjakefala posted above should work to port macros from the v2.x macros.tsv file, to the new macros.jsonl file.  Please let us know if there are other issues with macros or the input history.

**Closed as completed by saulpw** 2023-12-22 00:01 UTC
Labels: bug, fixed

**Comment by frosencrantz** [comment] 2023-12-23 00:02
It looks like it works.  I missed the message on this issue before I tried using the new change and noticed that my macros were missing, then I  to manually move it into place, and that did not work.  I tried to use the `gm`command to visit the macro sheet, but it was giving stack traces.   It looks like those traces are gone now

```
Traceback (most recent call last):
  File "usr/lib/python3.9/site-packages/visidata/threads.py", line 219, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "usr/lib/python3.9/site-packages/visidata/macros.py", line 129, in run
    for r in vd.macros_list:
  File "usr/lib/python3.9/site-packages/visidata/stored_prop.py", line 29, in _decorator
    value = json.loads(fp.read())
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I had already moved to the intermediate format macros_list.json and had to convert manually, renaming the two columns and saving as a jsonl file.

It does look like input_history is working well again.

Thanks @saulpw  and @anjakefala !!
