### ISSUE TITLE
[reload] Reload deletes tables created in visidata

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#438] opened 2020-01-06 13:36 UTC
**Small description**
Created a table with "A" command, added some rows, and hit reload table.  All rows were deleted, columns appeared untouched.

**Expected result**
Unclear.  Perhaps the behavior is correct.
I think doing nothing would have been correct.  Reloading a table from STDIN appears to do nothing.  So was surprised to lose data entered directly to visidata.

If this actually was correct behavior:
I added columns after creating the table, but these added columns remained after reload despite the rows being removed.   If reload is suppose to get back to the base state, it seems like the new columns should have been removed too.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
```
sheet   col     row     longname        input   keystrokes      comment
VisiData_Main_Menu                      add-sheet       3       A
unnamed                 add-row         a
unnamed 0       0       edit-cell       a:b:c   e
unnamed                 reload-sheet            ^R
```
**Additional context**
I was trying to debug something with a colorizer, so created a simple table, and hit reload thinking that might help with my color issue, but it deleted the rows, which was unexpected.  Undo doesn't work on reload.

Please include the version of VisiData.
Head version of develop. v2.2

**Comment by anjakefala** [comment] 2020-01-06 16:06
Hi @frosencrantz! 

If you are trying to see if a "refresh" of some kind will help with an aesthetic issue, `Ctrl+L` will "redraw" the current visible view. That is a safer bet than `reload` for your use-case.

Unfortunately, this is expected behaviour. `Reload` by design "restarts" the sheet. It goes through the steps that each sheet went through when it was initially loaded. With sheets associated with a data source, that means they reload that data source, undoing all changes **that have not been saved back to that original source**. With blank sheets, you return to a blank sheet. 

Maybe @saulpw has more to add? Based on my understanding of `reload` functionality, I am going to close this issue. =)

**Closed as completed by anjakefala** 2020-01-06 16:06 UTC

**Comment by frosencrantz** [comment] 2020-01-08 06:36
Hi @anjakefala   I think that is a reasonable take, and partly expected it.  I'm fine with it.   I do have a couple comments below for some additional thoughts. 

Yes, what I should have used was redraw, thanks for pointing that out. It did not occur to me then.

I'll mention being on the losing end of the data (just a couple rows) is shocking.  Even though my data in this case was only to debug something.

There were a couple things that seem like irregularities about this:
* Reloading data from stdin doesn't seem to do anything.

*  You can't see it from the vd data I showed, but after adding the first cell, I split the column by colon.  This added several additional columns.  When I did the reload, the new columns remained, but not the data.  This seemed inconsistent.  It seemed like if reload goes back to the initial state it should have gone back to the initial configuration removing the columns added by split.

**Comment by anjakefala** [comment] 2020-01-08 07:21
```quote
Reloading data from stdin doesn't seem to do anything.
```

I did:

```
ls -al | bin/vd -f fixed
```
and then modified a cell, pressed `^R`, and it reloaded to what I had originally piped in. Can you walk me through what you did and saw? (I did this all on the `develop` branch.)

**Comment by anjakefala** [comment] 2020-01-08 07:44
```quote
You can't see it from the vd data I showed, but after adding the first cell, I split the column by colon. This added several additional columns. When I did the reload, the new columns remained, but not the data. This seemed inconsistent. It seemed like if reload goes back to the initial state it should have gone back to the initial configuration removing the columns added by split.
```

@saulpw?

**Comment by frosencrantz** [comment] 2020-01-09 06:08
Yes, looks like I was wrong about the table from stdin.  I had not made any edits, so the table appeared unchanged.  But trying again now it appears that reload on stdin loses all edits (including new columns.)
