### ISSUE TITLE
Table view is blank when table saved from .tsv to .vds - I think there is data but it is invisible

### ISSUE THREAD

**Issue by AaronFeldman** [saulpw/visidata#2198] opened 2023-12-30 02:19 UTC
**Brief Description**

When I save to .vds from an existing .tsv file the screen is blank
Version 2.11,1

**Expected result**

For data to be visible in the table view

**Actual result with screenshot**

![Screenshot from 2023-12-29 21-09-25](https://github.com/saulpw/visidata/assets/5024267/655e3834-8789-434a-9556-6eab1cfbe5d7)

If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

'Ctrl-E' only produces "no error" message

**Steps to reproduce with sample data and a .vd**

1. Make a database
2. Save it as a .tsv file
3. Close the file and quit
4. open the file
5. save the file as a .vds file
6. close the file
7. open the .vds file and there is no visible data in the table view

First try reproducing without any user configuration by using the flag `-N`.
e.g. `echo "abc" | vd -f txt -N`

Same result from visidata -N

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

No steps led to the issue except opening the .vds file after it was saved

**Additional context**
Please include the version of VisiData and Python.
Version 2.11,1
Python 3.10.12
-Shift O-  changing the colors did not help
I could tell the data was there because I could enter the row view and read the data for each individual row

[RolfClients.txt](https://github.com/saulpw/visidata/files/13796900/RolfClients.txt)

**Comment by saulpw** [comment] 2023-12-30 06:17
I think this is a duplicate of #2046.  @AaronFeldman can you try with the latest develop?  We're about to ship 3.0 and so if this is still a bug we'd like to address it.

**Comment by AaronFeldman** [comment] 2023-12-30 19:59
> I think this is a duplicate of #2046. @AaronFeldman can you try with the latest develop? We're about to ship 3.0 and so if this is still a bug we'd like to address it.

Thank you for your quick reply!  So I installed VisiData 3.1dev and slightly different but same result when I tried to open up the previously save .vds file.

But, when I resaved it as a .vds it was correct.  So it was the "save as" that did it to begin with. Thank you!!

**Closed as completed** 2023-12-30 22:14 UTC
Labels: bug, fixed
