### ISSUE TITLE
[docs] Broken link to color docs

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#1735] opened 2023-02-15 10:19 UTC
**Small description**

This section of the docs:
https://www.visidata.org/docs/api/interface#colors

Links to this page:
https://www.visidata.org/docs/colors

But it does not exist!

<img width="179" alt="Screen Shot 2023-02-15 at 9 17 41 pm" src="https://user-images.githubusercontent.com/2499066/218999835-18da65eb-da59-4db4-8b4c-8ff09dc902f3.png">

**Expected result**

The link would exist.

**Actual result with screenshot**

404

<img width="344" alt="Screen Shot 2023-02-15 at 9 18 54 pm" src="https://user-images.githubusercontent.com/2499066/219000115-b02341cc-7a92-4ff2-ba88-3bd17fa4d088.png">

**Comment by ybc37** [comment] 2023-02-24 16:01
Duplicate of #1570.

**Comment by anjakefala** [comment] 2023-03-04 06:59
We are going to track this in #1570, which is a bit more comprehensive! Thanks for letting us know.

**Closed as completed by anjakefala** 2023-03-04 06:59 UTC
Labels: bug
