### ISSUE TITLE
[wishlist option] Have commands (like g*) work on all rows if none selected

### ISSUE THREAD

**Issue by maufdez** [saulpw/visidata#767] opened 2020-11-04 15:42 UTC
**Small description**
Since rev2.0.1 g* does not work if no rows are selected.
**Expected result**
In 1.5.2 g* would work (do regex replacement in place) without selecting any rows. I did not expect this to change on 2.0.1, I'm not sure if this is intentional but now I have to do gs g* instead.
**Actual result with screenshot**
"no rows selected" is shown in the status line (bottom).

**Steps to reproduce with sample data and a .vd**
Load any datasheet go to a column and type g*

**Additional context**
Worked on 1.5.2
Stopped working on 2.0.1

**Comment by anjakefala** [comment] 2020-11-04 17:29
Hi @maufdez!

This is by design. We are moving to a framework of doing "selected rows" instead of "selected rows and all rows". If someone is using VisiData in a pipeline in batch mode, we want VisiData to behave predictably.

**Comment by anjakefala** [comment] 2020-11-05 04:28
Hi @maufdez and everyone else,

Since this is a popular request, Saul and I are going to explore making an option. 

The idea is that the default behaviour will remain the safe `selectedRows or fail()`, but users will be able to flip the option to get the classic `selectedRows or rows` in interactive mode.  Batch mode will use plain `selectedRows` even if it is empty.

The details are stil to be ironed out, but this is the intention. =)

**Comment by maufdez** [comment] 2020-11-05 15:27
Thanks, I use visidata daiy (one of the best things ever for my type of work), and have some automation through recordings, this new behaviour took me by surprise and I wanted to know if I needed to change my recordings, which I think I have to based on what you just said. If you are going to enable the old behavior as optional it would be nice to be able to set it in your .visidata or in the command line, in order to make your existing recordings using that old behavior to keep working.

**Comment by saulpw** [comment] 2020-11-05 19:07
Hi @maufdez, can you explain your use case with this automation?  Do you actually *want* `selectedRows or rows` in batch mode?  How does that work for you?

**Comment by maufdez** [comment] 2020-11-09 21:09
Sorry for the long time to respons, I have not checked the issues in github for a while. My use case is probably uniq, I work with output from a couple of data bases, and I have to compare them, they are stored for me as a couple of csvs, there is some variation in the data, which is pre-worked using [miller](https://miller.readthedocs.io/en/latest/index.html), then I programmatically generate a recording using some templates inside a perl script, ant then call mlr with the generated recording. This basically compares columns to each other giving me calculated columns that evaluate how good the matching between columns is, and then I can apply transformations to a column and see those columns change accordingly, which allows us to write automation jobs to tranform one into the other.
I know it sounds complicated, but miller and visidata combined are making my job much easier than what I was doing before.
I actually checked my templates and none were using the g*, or g= commands, I mainly use them to do transformations on the flight after my comparison sheet has been generated. So it is a matter of re-training the people who use this for analysis.

**Comment by saulpw** [comment] 2020-11-09 23:10
That's okay.  We can add an option for interactive mode that works as before, especially because I find myself missing it too :)  But batch mode will need to continue to work as it is, so if you use `g*` or `g=` or others like it while this option is enabled, the results in batch mode may be different from the results in interactive mode.

**Comment by maufdez** [comment] 2020-11-09 23:35
Excellent! Thanks, I think that as long as we know what each behavior is, that is a good solution.

**Comment by anjakefala** [comment] 2020-11-30 05:23
Okay! I added an option.

On `develop`, there is an option `some_selected_rows`. If you set it to *True* in your `~/,visidatarc`, then certain commands will operate on 'all rows if none are selected'. In batch mode, those commands will still only execute with rows that are actually selected.

```
options.some_selected_rows = True
```

So far, those commands are `g*` and `gz*`. We welcome user feedback on which other commands this should also apply to.

This option is just a placeholder name, and we need to come up with a better idea.

Some brainstormed ideas:

    empty_select_rows
    empty_select_fail
    empty_select_all_rows
    none_select_*
    selected_or_rows
    some_selected_rows

**Closed as completed by anjakefala** 2020-11-30 05:23 UTC
Labels: wishlist, wish granted, By Design
