### ISSUE TITLE
Dubious test failure on Python 3.12.4: edit-type, describe, describe-error

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#2447] opened 2024-07-10 13:19 UTC
A Nix user on MacOS has reported the following issue:
https://github.com/NixOS/nixpkgs/issues/326083

tests/edit-type is failing for them due to a floating point number not matching
exactly the golden value.

```patch
index 3a5decf..5c68fcc 100644
--- a/tests/golden/edit-type.tsv
+++ b/tests/golden/edit-type.tsv
@@ -4,5 +4,5 @@ Customer     0       0       17
 SKU        0       0       34                                              
 Item 0       0       40                                              
 Quantity     0       0       10      1       144     403     2       7.90    21.57
-Unit    0       0       28      0.0     2495.99 11974.530000000006      12.95   234.79  585.85
+Unit   0       0       28      0.0     2495.99 11974.53        12.95   234.79  585.85
 Paid   0       0       36      -2300.0 3602.1  10886.21        51.8    213.46  819.74
```

CC: @victorhooi

Visidata 3.0.2
Python 3.12.4
Issue seeming to happen on both aarch64-darwin and x86_64-linux

**Comment by anjakefala** [comment] 2024-07-11 15:28
From @pacien 

    And I could have sworn visidata was working for me last week or
    so, before I ran nix flake update since then...although maybe
    I'm mistaken...

Thinking about it, python3 in nixpkgs has switched from python311 to
python312 last month.

I managed to reproduce the issue locally as well,
confirming that something changed between those versions of Python.

This failure seems to be happening only with Python 3.12.4.
The test suite passes fine with Python 3.11.9 however.

The failing tests are:

    describe-error
    describe
    edit-type

All failing the same way with the number rounding.

    Do you, by any chance have options.disp_float_fmt set to anything?

The tests are executed in a sandboxed environment with Nix,
so user config should not affect those.

**Comment by anjakefala** [comment] 2024-07-13 04:54
Hey @pacien!

I just pushed a fix to `develop`. =) The tests should now pass.

An official release is in the works!

**Closed as completed** 2024-07-13 04:54 UTC
Labels: bug, fixed
