### ISSUE TITLE
[2.0.1] long commands set in alias() are not auto-completable in exec-longname

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#841] opened 2020-12-13 09:07 UTC
**Small description**
If I use the following to set a new command, then alias it to a shortened command, the short command is not auto-complete-able when running `exec-longname`.

```
Sheet.addCommand(None, 'addcol-ubercmd-xyz', 'cursorCol.ubercommand()')
alias('ubercmd', 'addcol-ubercmd-xyz')
```

**Expected result**
All alias commands to be tab completeable, otherwise it could take longer to type out the "shorter" command than using the tab complete of the "longer" command

**Comment by anjakefala** [comment] 2020-12-21 18:24
The issue is that `alias()` adds an association to `bindkeys`, but not to `vd.commands`. Auto-complete are pulled from `vd.commands`.

To accommodate this, we will need to identify longnames that are being alias'd, and add them to `vd.commands`.

The longname you used as an example would currently not be identified as a longname, because it lacks a `-`. To accommodate it, we should also expand `vd.isLongname` to check if a string is all lowercase, and longer than 3 characters.

**Comment by anjakefala** [comment] 2020-12-22 03:43
Hi @geekscrapy!

After investigating this, I determined that this would be a lot of work. There is no single comprehensive list of longnames. Longnames are either in bindkeys (sometimes several levels down) or in vd.commands. To fix this bug would require reworking how we track longnames, which is a pretty big restructure task.

After talking to Saul, we have determined that that is a worthwhile undertaking to do, but one that we are not going to at the moment prioritise over other undertakings. We are going to kondo and close this for now, and add it to our roadmap. If anyone wants to keep this issue open, they can subscribe to [Saul's patreon](https://www.patreon.com/saulpw/posts).

**Closed as completed by anjakefala** 2020-12-22 03:43 UTC
Labels: bug
